package mnj.mfg.model.services.client;

import mnj.mfg.model.services.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 23 17:25:42 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public String copyRecords(String type, String headerId, String lineId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"copyRecords",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {type, headerId, lineId});
        return (String)_ret;
    }

    public String createItems(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createItems",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public double getCostProdPerLine(String name, String projectionNo) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCostProdPerLine",new String [] {"java.lang.String","java.lang.String"},new Object[] {name, projectionNo});
        return ((Double)_ret).doubleValue();
    }

    public String createOrder(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createOrder",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public String updateOrder(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateOrder",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public void ApproveNForward(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"ApproveNForward",new String [] {"java.lang.String"},new Object[] {headerId});
        return;
    }

    public void Approve(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"Approve",new String [] {"java.lang.String"},new Object[] {headerId});
        return;
    }

    public Row createLines() {
        Object _ret = this.riInvokeExportedMethod(this,"createLines",null,null);
        return (Row)_ret;
    }

    public void CopyPrecost(String type) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CopyPrecost",new String [] {"java.lang.String"},new Object[] {type});
        return;
    }

    public void MakeLinesClone() {
        Object _ret = this.riInvokeExportedMethod(this,"MakeLinesClone",null,null);
        return;
    }

    public void setSessionValues(String userId, String orgId, String respId,
                                 String respApplId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, orgId, respId, respApplId});
        return;
    }

    public void refreshProdCostLineWise(String unitName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshProdCostLineWise",new String [] {"java.lang.String"},new Object[] {unitName});
        return;
    }

    public double getPOCFinCost(String type) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPOCFinCost",new String [] {"java.lang.String"},new Object[] {type});
        return ((Double)_ret).doubleValue();
    }

    public double getProdCostUnitWise(String unitName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getProdCostUnitWise",new String [] {"java.lang.String"},new Object[] {unitName});
        return ((Double)_ret).doubleValue();
    }

    public void createBPODetailRow() {
        Object _ret =
            this.riInvokeExportedMethod(this,"createBPODetailRow",null,null);
        return;
    }

    public String createOrderLines(String headerId, String lineId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createOrderLines",new String [] {"java.lang.String","java.lang.String"},new Object[] {headerId, lineId});
        return (String)_ret;
    }

    public void refreshCreateBPODetail() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshCreateBPODetail",null,null);
        return;
    }

    public String createTBAOrder(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createTBAOrder",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public String UpdateBPO(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"UpdateBPO",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public String CancelBPO(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CancelBPO",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public double getBPOQty_Tot() {
        Object _ret = this.riInvokeExportedMethod(this,"getBPOQty_Tot",null,null);
        return ((Double)_ret).doubleValue();
    }

    public void UploadBPO_Block() {
        Object _ret =
            this.riInvokeExportedMethod(this,"UploadBPO_Block",null,null);
        return;
    }

    public void CopyAllPrecost(String type) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CopyAllPrecost",new String [] {"java.lang.String"},new Object[] {type});
        return;
    }

    public void ClearTempUploadBlock() {
        Object _ret =
            this.riInvokeExportedMethod(this,"ClearTempUploadBlock",null,null);
        return;
    }

    public void CopyItemsDetail() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CopyItemsDetail",null,null);
        return;
    }

    public void StyleTracking() {
        Object _ret = this.riInvokeExportedMethod(this,"StyleTracking",null,null);
        return;
    }
}
