package mnj.mfg.model.views.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 17:41:02 BDT 2015
// ---------------------------------------------------------------------
public interface MnjMfgPrecostingLView extends ViewObject {
    void ExecuteLines(String POC);
}
