package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 07 16:40:44 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BomBpoLinesAllVoViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BomBpoLinesAllVoViewImpl() {
    }
}
