package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgPrecostingDryDImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 08 00:35:11 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DryDetailVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DryDetailVORowImpl() {
    }

    /**
     * Gets MnjMfgPrecostingDryD entity object.
     * @return the MnjMfgPrecostingDryD
     */
    public MnjMfgPrecostingDryDImpl getMnjMfgPrecostingDryD() {
        return (MnjMfgPrecostingDryDImpl)getEntity(0);
    }
}
