package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 08 14:44:02 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjBomBpoLinesAllViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjBomBpoLinesAllViewImpl() {
    }
}
