package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjBomBpoLinesAllImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 08 14:44:02 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjBomBpoLinesAllViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BomId {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getBomId();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setBomId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        SaleOrderId {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getSaleOrderId();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setSaleOrderId((Number)value);
            }
        }
        ,
        SealeNo {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getSealeNo();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setSealeNo((String)value);
            }
        }
        ,
        Brand {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getBrand();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        StyleNo {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getStyleNo();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setStyleNo((String)value);
            }
        }
        ,
        UserItemDesc {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getUserItemDesc();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setUserItemDesc((String)value);
            }
        }
        ,
        EndUserDesc {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getEndUserDesc();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setEndUserDesc((String)value);
            }
        }
        ,
        OrderQty {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        Fit {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getFit();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setFit((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Percent {
            public Object get(MnjBomBpoLinesAllViewRowImpl obj) {
                return obj.getPercent();
            }

            public void put(MnjBomBpoLinesAllViewRowImpl obj, Object value) {
                obj.setPercent((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjBomBpoLinesAllViewRowImpl object);

        public abstract void put(MnjBomBpoLinesAllViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BOMID = AttributesEnum.BomId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int SALEORDERID = AttributesEnum.SaleOrderId.index();
    public static final int SEALENO = AttributesEnum.SealeNo.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int STYLENO = AttributesEnum.StyleNo.index();
    public static final int USERITEMDESC = AttributesEnum.UserItemDesc.index();
    public static final int ENDUSERDESC = AttributesEnum.EndUserDesc.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int FIT = AttributesEnum.Fit.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int PERCENT = AttributesEnum.Percent.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjBomBpoLinesAllViewRowImpl() {
    }

    /**
     * Gets MnjBomBpoLinesAll entity object.
     * @return the MnjBomBpoLinesAll
     */
    public MnjBomBpoLinesAllImpl getMnjBomBpoLinesAll() {
        return (MnjBomBpoLinesAllImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BOM_ID using the alias name BomId.
     * @return the BOM_ID
     */
    public Number getBomId() {
        return (Number) getAttributeInternal(BOMID);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_ID using the alias name BomId.
     * @param value value to set the BOM_ID
     */
    public void setBomId(Number value) {
        setAttributeInternal(BOMID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for BPO_NO using the alias name BpoNo.
     * @return the BPO_NO
     */
    public String getBpoNo() {
        return (String) getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_NO using the alias name BpoNo.
     * @param value value to set the BPO_NO
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for SALE_ORDER_ID using the alias name SaleOrderId.
     * @return the SALE_ORDER_ID
     */
    public Number getSaleOrderId() {
        return (Number) getAttributeInternal(SALEORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_ORDER_ID using the alias name SaleOrderId.
     * @param value value to set the SALE_ORDER_ID
     */
    public void setSaleOrderId(Number value) {
        setAttributeInternal(SALEORDERID, value);
    }

    /**
     * Gets the attribute value for SEALE_NO using the alias name SealeNo.
     * @return the SEALE_NO
     */
    public String getSealeNo() {
        return (String) getAttributeInternal(SEALENO);
    }

    /**
     * Sets <code>value</code> as attribute value for SEALE_NO using the alias name SealeNo.
     * @param value value to set the SEALE_NO
     */
    public void setSealeNo(String value) {
        setAttributeInternal(SEALENO, value);
    }

    /**
     * Gets the attribute value for BRAND using the alias name Brand.
     * @return the BRAND
     */
    public String getBrand() {
        return (String) getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as attribute value for BRAND using the alias name Brand.
     * @param value value to set the BRAND
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for STYLE_NO using the alias name StyleNo.
     * @return the STYLE_NO
     */
    public String getStyleNo() {
        return (String) getAttributeInternal(STYLENO);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NO using the alias name StyleNo.
     * @param value value to set the STYLE_NO
     */
    public void setStyleNo(String value) {
        setAttributeInternal(STYLENO, value);
    }

    /**
     * Gets the attribute value for USER_ITEM_DESC using the alias name UserItemDesc.
     * @return the USER_ITEM_DESC
     */
    public String getUserItemDesc() {
        return (String) getAttributeInternal(USERITEMDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ITEM_DESC using the alias name UserItemDesc.
     * @param value value to set the USER_ITEM_DESC
     */
    public void setUserItemDesc(String value) {
        setAttributeInternal(USERITEMDESC, value);
    }

    /**
     * Gets the attribute value for END_USER_DESC using the alias name EndUserDesc.
     * @return the END_USER_DESC
     */
    public String getEndUserDesc() {
        return (String) getAttributeInternal(ENDUSERDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for END_USER_DESC using the alias name EndUserDesc.
     * @param value value to set the END_USER_DESC
     */
    public void setEndUserDesc(String value) {
        setAttributeInternal(ENDUSERDESC, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for FIT using the alias name Fit.
     * @return the FIT
     */
    public String getFit() {
        return (String) getAttributeInternal(FIT);
    }

    /**
     * Sets <code>value</code> as attribute value for FIT using the alias name Fit.
     * @param value value to set the FIT
     */
    public void setFit(String value) {
        setAttributeInternal(FIT, value);
    }

    /**
     * Gets the attribute value for SEASON using the alias name Season.
     * @return the SEASON
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON using the alias name Season.
     * @param value value to set the SEASON
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for PERCENT using the alias name Percent.
     * @return the PERCENT
     */
    public Number getPercent() {
        return (Number) getAttributeInternal(PERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for PERCENT using the alias name Percent.
     * @param value value to set the PERCENT
     */
    public void setPercent(Number value) {
        setAttributeInternal(PERCENT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
