package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgPrecostingLImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 09 17:57:29 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingLViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        HeaderNumber {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getHeaderNumber();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setHeaderNumber((Number)value);
            }
        }
        ,
        WashName {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWashName();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        Colour {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getColour();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setColour((String)value);
            }
        }
        ,
        Rate {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getRate();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setRate((Number)value);
            }
        }
        ,
        FobWitoutComm {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFobWitoutComm();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFobWitoutComm((Number)value);
            }
        }
        ,
        FobWithComm {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFobWithComm();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFobWithComm((Number)value);
            }
        }
        ,
        FobWithSmsSample {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFobWithSmsSample();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFobWithSmsSample((Number)value);
            }
        }
        ,
        CmMerchandiser {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCmMerchandiser();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCmMerchandiser((Number)value);
            }
        }
        ,
        ReflectProfit {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getReflectProfit();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setReflectProfit((Number)value);
            }
        }
        ,
        Cost {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCost();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCost((Number)value);
            }
        }
        ,
        Finance {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFinance();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFinance((Number)value);
            }
        }
        ,
        Profit {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getProfit();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setProfit((Number)value);
            }
        }
        ,
        Cm {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCm();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCm((Number)value);
            }
        }
        ,
        ProdCostHour {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getProdCostHour();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setProdCostHour((Number)value);
            }
        }
        ,
        ProdPerHour {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getProdPerHour();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setProdPerHour((Number)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        BpoQty {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getBpoQty();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setBpoQty((Number)value);
            }
        }
        ,
        ItemId {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getItemId();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        Flag {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFlag();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFlag((String)value);
            }
        }
        ,
        PoType {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getPoType();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setPoType((String)value);
            }
        }
        ,
        OtherCharge {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getOtherCharge();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setOtherCharge((Number)value);
            }
        }
        ,
        LabTestCharge {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getLabTestCharge();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setLabTestCharge((Number)value);
            }
        }
        ,
        Print {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getPrint();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setPrint((Number)value);
            }
        }
        ,
        FabricFinance {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFabricFinance();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFabricFinance((Number)value);
            }
        }
        ,
        WashFinance {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWashFinance();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWashFinance((Number)value);
            }
        }
        ,
        TrimFinance {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getTrimFinance();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setTrimFinance((Number)value);
            }
        }
        ,
        CommisonPrcnt {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCommisonPrcnt();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCommisonPrcnt((Number)value);
            }
        }
        ,
        SmsQty {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getSmsQty();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setSmsQty((Number)value);
            }
        }
        ,
        FabricDesc {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFabricDesc();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFabricDesc((String)value);
            }
        }
        ,
        CloneFlag {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCloneFlag();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCloneFlag((String)value);
            }
        }
        ,
        Fob {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFob();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFob((Number)value);
            }
        }
        ,
        FabricCost {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFabricCost();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFabricCost((Number)value);
            }
        }
        ,
        TrimCost {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getTrimCost();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setTrimCost((Number)value);
            }
        }
        ,
        WashCost {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWashCost();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWashCost((Number)value);
            }
        }
        ,
        TargetPrice {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getTargetPrice();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setTargetPrice((Number)value);
            }
        }
        ,
        Difference {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getDifference();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setDifference((Number)value);
            }
        }
        ,
        Others {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getOthers();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setOthers((Number)value);
            }
        }
        ,
        ChildStyleNo {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getChildStyleNo();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setChildStyleNo((String)value);
            }
        }
        ,
        Weight {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWeight();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWeight((String)value);
            }
        }
        ,
        WeightType {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWeightType();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWeightType((String)value);
            }
        }
        ,
        WidthType {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWidthType();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWidthType((String)value);
            }
        }
        ,
        WidthValue {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWidthValue();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWidthValue((Number)value);
            }
        }
        ,
        FabricFinsih {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFabricFinsih();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFabricFinsih((String)value);
            }
        }
        ,
        Elongation {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getElongation();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setElongation((String)value);
            }
        }
        ,
        FabricContent {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFabricContent();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFabricContent((String)value);
            }
        }
        ,
        ShipMode {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getShipMode();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setShipMode((String)value);
            }
        }
        ,
        Country {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCountry();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        FinalFinishGoodsColour {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFinalFinishGoodsColour();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFinalFinishGoodsColour((String)value);
            }
        }
        ,
        DeliveryEndDate {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getDeliveryEndDate();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setDeliveryEndDate((Date)value);
            }
        }
        ,
        CmMerchand {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCmMerchand();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCmMerchand((String)value);
            }
        }
        ,
        ProdPerLinePerH {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getProdPerLinePerH();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setProdPerLinePerH((Number)value);
            }
        }
        ,
        StyleEfficiency {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getStyleEfficiency();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setStyleEfficiency((Number)value);
            }
        }
        ,
        Sam {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getSam();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setSam((Number)value);
            }
        }
        ,
        Smv {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getSmv();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setSmv((String)value);
            }
        }
        ,
        CostNew {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCostNew();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCostNew((Number)value);
            }
        }
        ,
        FactoryAvgEf {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getFactoryAvgEf();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setFactoryAvgEf((String)value);
            }
        }
        ,
        ProdCostLinePerH {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getProdCostLinePerH();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setProdCostLinePerH((Number)value);
            }
        }
        ,
        CmManagement {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getCmManagement();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setCmManagement((Number)value);
            }
        }
        ,
        TotalCost {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getTotalCost();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setTotalCost((Number)value);
            }
        }
        ,
        ReplaceBpo {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getReplaceBpo();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setReplaceBpo((String)value);
            }
        }
        ,
        DeliveryStartDate {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getDeliveryStartDate();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setDeliveryStartDate((Date)value);
            }
        }
        ,
        ReplaceWash {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getReplaceWash();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setReplaceWash((String)value);
            }
        }
        ,
        ItemTotal {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getItemTotal();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setItemTotal((Number)value);
            }
        }
        ,
        WetTotal {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getWetTotal();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setWetTotal((Number)value);
            }
        }
        ,
        DryTotal {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getDryTotal();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setDryTotal((String)value);
            }
        }
        ,
        MnjMfgPrecostingItemDView {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getMnjMfgPrecostingItemDView();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgPrecostingCountryDView {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getMnjMfgPrecostingCountryDView();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgPrecostingWetDView {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getMnjMfgPrecostingWetDView();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DryDetailVO {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getDryDetailVO();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdateOrderInterface {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getUpdateOrderInterface();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgPrecostingHView {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getMnjMfgPrecostingHView();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ColorLOv1 {
            public Object get(MnjMfgPrecostingLViewRowImpl obj) {
                return obj.getColorLOv1();
            }

            public void put(MnjMfgPrecostingLViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgPrecostingLViewRowImpl object);

        public abstract void put(MnjMfgPrecostingLViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int HEADERNUMBER = AttributesEnum.HeaderNumber.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int COLOUR = AttributesEnum.Colour.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int FOBWITOUTCOMM = AttributesEnum.FobWitoutComm.index();
    public static final int FOBWITHCOMM = AttributesEnum.FobWithComm.index();
    public static final int FOBWITHSMSSAMPLE = AttributesEnum.FobWithSmsSample.index();
    public static final int CMMERCHANDISER = AttributesEnum.CmMerchandiser.index();
    public static final int REFLECTPROFIT = AttributesEnum.ReflectProfit.index();
    public static final int COST = AttributesEnum.Cost.index();
    public static final int FINANCE = AttributesEnum.Finance.index();
    public static final int PROFIT = AttributesEnum.Profit.index();
    public static final int CM = AttributesEnum.Cm.index();
    public static final int PRODCOSTHOUR = AttributesEnum.ProdCostHour.index();
    public static final int PRODPERHOUR = AttributesEnum.ProdPerHour.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int BPOQTY = AttributesEnum.BpoQty.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int FLAG = AttributesEnum.Flag.index();
    public static final int POTYPE = AttributesEnum.PoType.index();
    public static final int OTHERCHARGE = AttributesEnum.OtherCharge.index();
    public static final int LABTESTCHARGE = AttributesEnum.LabTestCharge.index();
    public static final int PRINT = AttributesEnum.Print.index();
    public static final int FABRICFINANCE = AttributesEnum.FabricFinance.index();
    public static final int WASHFINANCE = AttributesEnum.WashFinance.index();
    public static final int TRIMFINANCE = AttributesEnum.TrimFinance.index();
    public static final int COMMISONPRCNT = AttributesEnum.CommisonPrcnt.index();
    public static final int SMSQTY = AttributesEnum.SmsQty.index();
    public static final int FABRICDESC = AttributesEnum.FabricDesc.index();
    public static final int CLONEFLAG = AttributesEnum.CloneFlag.index();
    public static final int FOB = AttributesEnum.Fob.index();
    public static final int FABRICCOST = AttributesEnum.FabricCost.index();
    public static final int TRIMCOST = AttributesEnum.TrimCost.index();
    public static final int WASHCOST = AttributesEnum.WashCost.index();
    public static final int TARGETPRICE = AttributesEnum.TargetPrice.index();
    public static final int DIFFERENCE = AttributesEnum.Difference.index();
    public static final int OTHERS = AttributesEnum.Others.index();
    public static final int CHILDSTYLENO = AttributesEnum.ChildStyleNo.index();
    public static final int WEIGHT = AttributesEnum.Weight.index();
    public static final int WEIGHTTYPE = AttributesEnum.WeightType.index();
    public static final int WIDTHTYPE = AttributesEnum.WidthType.index();
    public static final int WIDTHVALUE = AttributesEnum.WidthValue.index();
    public static final int FABRICFINSIH = AttributesEnum.FabricFinsih.index();
    public static final int ELONGATION = AttributesEnum.Elongation.index();
    public static final int FABRICCONTENT = AttributesEnum.FabricContent.index();
    public static final int SHIPMODE = AttributesEnum.ShipMode.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int FINALFINISHGOODSCOLOUR = AttributesEnum.FinalFinishGoodsColour.index();
    public static final int DELIVERYENDDATE = AttributesEnum.DeliveryEndDate.index();
    public static final int CMMERCHAND = AttributesEnum.CmMerchand.index();
    public static final int PRODPERLINEPERH = AttributesEnum.ProdPerLinePerH.index();
    public static final int STYLEEFFICIENCY = AttributesEnum.StyleEfficiency.index();
    public static final int SAM = AttributesEnum.Sam.index();
    public static final int SMV = AttributesEnum.Smv.index();
    public static final int COSTNEW = AttributesEnum.CostNew.index();
    public static final int FACTORYAVGEF = AttributesEnum.FactoryAvgEf.index();
    public static final int PRODCOSTLINEPERH = AttributesEnum.ProdCostLinePerH.index();
    public static final int CMMANAGEMENT = AttributesEnum.CmManagement.index();
    public static final int TOTALCOST = AttributesEnum.TotalCost.index();
    public static final int REPLACEBPO = AttributesEnum.ReplaceBpo.index();
    public static final int DELIVERYSTARTDATE = AttributesEnum.DeliveryStartDate.index();
    public static final int REPLACEWASH = AttributesEnum.ReplaceWash.index();
    public static final int ITEMTOTAL = AttributesEnum.ItemTotal.index();
    public static final int WETTOTAL = AttributesEnum.WetTotal.index();
    public static final int DRYTOTAL = AttributesEnum.DryTotal.index();
    public static final int MNJMFGPRECOSTINGITEMDVIEW = AttributesEnum.MnjMfgPrecostingItemDView.index();
    public static final int MNJMFGPRECOSTINGCOUNTRYDVIEW = AttributesEnum.MnjMfgPrecostingCountryDView.index();
    public static final int MNJMFGPRECOSTINGWETDVIEW = AttributesEnum.MnjMfgPrecostingWetDView.index();
    public static final int DRYDETAILVO = AttributesEnum.DryDetailVO.index();
    public static final int UPDATEORDERINTERFACE = AttributesEnum.UpdateOrderInterface.index();
    public static final int MNJMFGPRECOSTINGHVIEW = AttributesEnum.MnjMfgPrecostingHView.index();
    public static final int COLORLOV1 = AttributesEnum.ColorLOv1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingLViewRowImpl() {
    }

    /**
     * Gets MnjMfgPrecostingL entity object.
     * @return the MnjMfgPrecostingL
     */
    public MnjMfgPrecostingLImpl getMnjMfgPrecostingL() {
        return (MnjMfgPrecostingLImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for HEADER_NUMBER using the alias name HeaderNumber.
     * @return the HEADER_NUMBER
     */
    public Number getHeaderNumber() {
        return (Number) getAttributeInternal(HEADERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_NUMBER using the alias name HeaderNumber.
     * @param value value to set the HEADER_NUMBER
     */
    public void setHeaderNumber(Number value) {
        setAttributeInternal(HEADERNUMBER, value);
    }

    /**
     * Gets the attribute value for WASH_NAME using the alias name WashName.
     * @return the WASH_NAME
     */
    public String getWashName() {
        return (String) getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_NAME using the alias name WashName.
     * @param value value to set the WASH_NAME
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for COLOUR using the alias name Colour.
     * @return the COLOUR
     */
    public String getColour() {
        return (String) getAttributeInternal(COLOUR);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOUR using the alias name Colour.
     * @param value value to set the COLOUR
     */
    public void setColour(String value) {
        setAttributeInternal(COLOUR, value);
    }

    /**
     * Gets the attribute value for RATE using the alias name Rate.
     * @return the RATE
     */
    public Number getRate() {
        return (Number) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RATE using the alias name Rate.
     * @param value value to set the RATE
     */
    public void setRate(Number value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for FOB_WITOUT_COMM using the alias name FobWitoutComm.
     * @return the FOB_WITOUT_COMM
     */
    public Number getFobWitoutComm() {
        return (Number) getAttributeInternal(FOBWITOUTCOMM);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_WITOUT_COMM using the alias name FobWitoutComm.
     * @param value value to set the FOB_WITOUT_COMM
     */
    public void setFobWitoutComm(Number value) {
        setAttributeInternal(FOBWITOUTCOMM, value);
    }

    /**
     * Gets the attribute value for FOB_WITH_COMM using the alias name FobWithComm.
     * @return the FOB_WITH_COMM
     */
    public Number getFobWithComm() {
        return (Number) getAttributeInternal(FOBWITHCOMM);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_WITH_COMM using the alias name FobWithComm.
     * @param value value to set the FOB_WITH_COMM
     */
    public void setFobWithComm(Number value) {
        setAttributeInternal(FOBWITHCOMM, value);
    }

    /**
     * Gets the attribute value for FOB_WITH_SMS_SAMPLE using the alias name FobWithSmsSample.
     * @return the FOB_WITH_SMS_SAMPLE
     */
    public Number getFobWithSmsSample() {
        return (Number) getAttributeInternal(FOBWITHSMSSAMPLE);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_WITH_SMS_SAMPLE using the alias name FobWithSmsSample.
     * @param value value to set the FOB_WITH_SMS_SAMPLE
     */
    public void setFobWithSmsSample(Number value) {
        setAttributeInternal(FOBWITHSMSSAMPLE, value);
    }

    /**
     * Gets the attribute value for CM_MERCHANDISER using the alias name CmMerchandiser.
     * @return the CM_MERCHANDISER
     */
    public Number getCmMerchandiser() {
        return (Number) getAttributeInternal(CMMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MERCHANDISER using the alias name CmMerchandiser.
     * @param value value to set the CM_MERCHANDISER
     */
    public void setCmMerchandiser(Number value) {
        setAttributeInternal(CMMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for REFLECT_PROFIT using the alias name ReflectProfit.
     * @return the REFLECT_PROFIT
     */
    public Number getReflectProfit() {
        return (Number) getAttributeInternal(REFLECTPROFIT);
    }

    /**
     * Sets <code>value</code> as attribute value for REFLECT_PROFIT using the alias name ReflectProfit.
     * @param value value to set the REFLECT_PROFIT
     */
    public void setReflectProfit(Number value) {
        setAttributeInternal(REFLECTPROFIT, value);
    }

    /**
     * Gets the attribute value for COST using the alias name Cost.
     * @return the COST
     */
    public Number getCost() {
        return (Number) getAttributeInternal(COST);
    }

    /**
     * Sets <code>value</code> as attribute value for COST using the alias name Cost.
     * @param value value to set the COST
     */
    public void setCost(Number value) {
        setAttributeInternal(COST, value);
    }

    /**
     * Gets the attribute value for FINANCE using the alias name Finance.
     * @return the FINANCE
     */
    public Number getFinance() {
        return (Number) getAttributeInternal(FINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for FINANCE using the alias name Finance.
     * @param value value to set the FINANCE
     */
    public void setFinance(Number value) {
        setAttributeInternal(FINANCE, value);
    }

    /**
     * Gets the attribute value for PROFIT using the alias name Profit.
     * @return the PROFIT
     */
    public Number getProfit() {
        return (Number) getAttributeInternal(PROFIT);
    }

    /**
     * Sets <code>value</code> as attribute value for PROFIT using the alias name Profit.
     * @param value value to set the PROFIT
     */
    public void setProfit(Number value) {
        setAttributeInternal(PROFIT, value);
    }

    /**
     * Gets the attribute value for CM using the alias name Cm.
     * @return the CM
     */
    public Number getCm() {
        return (Number) getAttributeInternal(CM);
    }

    /**
     * Sets <code>value</code> as attribute value for CM using the alias name Cm.
     * @param value value to set the CM
     */
    public void setCm(Number value) {
        setAttributeInternal(CM, value);
    }

    /**
     * Gets the attribute value for PROD_COST_HOUR using the alias name ProdCostHour.
     * @return the PROD_COST_HOUR
     */
    public Number getProdCostHour() {
        return (Number) getAttributeInternal(PRODCOSTHOUR);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_COST_HOUR using the alias name ProdCostHour.
     * @param value value to set the PROD_COST_HOUR
     */
    public void setProdCostHour(Number value) {
        setAttributeInternal(PRODCOSTHOUR, value);
    }

    /**
     * Gets the attribute value for PROD_PER_HOUR using the alias name ProdPerHour.
     * @return the PROD_PER_HOUR
     */
    public Number getProdPerHour() {
        return (Number) getAttributeInternal(PRODPERHOUR);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_PER_HOUR using the alias name ProdPerHour.
     * @param value value to set the PROD_PER_HOUR
     */
    public void setProdPerHour(Number value) {
        setAttributeInternal(PRODPERHOUR, value);
    }

    /**
     * Gets the attribute value for BPO_NO using the alias name BpoNo.
     * @return the BPO_NO
     */
    public String getBpoNo() {
        return (String) getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_NO using the alias name BpoNo.
     * @param value value to set the BPO_NO
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for BPO_QTY using the alias name BpoQty.
     * @return the BPO_QTY
     */
    public Number getBpoQty() {
        return (Number) getAttributeInternal(BPOQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_QTY using the alias name BpoQty.
     * @param value value to set the BPO_QTY
     */
    public void setBpoQty(Number value) {
        setAttributeInternal(BPOQTY, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for FLAG using the alias name Flag.
     * @return the FLAG
     */
    public String getFlag() {
        return (String) getAttributeInternal(FLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for FLAG using the alias name Flag.
     * @param value value to set the FLAG
     */
    public void setFlag(String value) {
        setAttributeInternal(FLAG, value);
    }

    /**
     * Gets the attribute value for PO_TYPE using the alias name PoType.
     * @return the PO_TYPE
     */
    public String getPoType() {
        return (String) getAttributeInternal(POTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_TYPE using the alias name PoType.
     * @param value value to set the PO_TYPE
     */
    public void setPoType(String value) {
        setAttributeInternal(POTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemTotal.
     * @return the ItemTotal
     */
    public Number getItemTotal() {
        return (Number) getAttributeInternal(ITEMTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemTotal.
     * @param value value to set the  ItemTotal
     */
    public void setItemTotal(Number value) {
        setAttributeInternal(ITEMTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WetTotal.
     * @return the WetTotal
     */
    public Number getWetTotal() {
        return (Number) getAttributeInternal(WETTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WetTotal.
     * @param value value to set the  WetTotal
     */
    public void setWetTotal(Number value) {
        setAttributeInternal(WETTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DryTotal.
     * @return the DryTotal
     */
    public String getDryTotal() {
        return (String) getAttributeInternal(DRYTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DryTotal.
     * @param value value to set the  DryTotal
     */
    public void setDryTotal(String value) {
        setAttributeInternal(DRYTOTAL, value);
    }

    /**
     * Gets the attribute value for CM_MANAGEMENT using the alias name CmManagement.
     * @return the CM_MANAGEMENT
     */
    public Number getCmManagement() {
        return (Number) getAttributeInternal(CMMANAGEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MANAGEMENT using the alias name CmManagement.
     * @param value value to set the CM_MANAGEMENT
     */
    public void setCmManagement(Number value) {
        setAttributeInternal(CMMANAGEMENT, value);
    }

    /**
     * Gets the attribute value for TOTAL_COST using the alias name TotalCost.
     * @return the TOTAL_COST
     */
    public Number getTotalCost() {
        return (Number) getAttributeInternal(TOTALCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_COST using the alias name TotalCost.
     * @param value value to set the TOTAL_COST
     */
    public void setTotalCost(Number value) {
        setAttributeInternal(TOTALCOST, value);
    }

    /**
     * Gets the attribute value for CM_MERCHAND using the alias name CmMerchand.
     * @return the CM_MERCHAND
     */
    public String getCmMerchand() {
        return (String) getAttributeInternal(CMMERCHAND);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MERCHAND using the alias name CmMerchand.
     * @param value value to set the CM_MERCHAND
     */
    public void setCmMerchand(String value) {
        setAttributeInternal(CMMERCHAND, value);
    }

    /**
     * Gets the attribute value for PROD_PER_LINE_PER_H using the alias name ProdPerLinePerH.
     * @return the PROD_PER_LINE_PER_H
     */
    public Number getProdPerLinePerH() {
        return (Number) getAttributeInternal(PRODPERLINEPERH);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_PER_LINE_PER_H using the alias name ProdPerLinePerH.
     * @param value value to set the PROD_PER_LINE_PER_H
     */
    public void setProdPerLinePerH(Number value) {
        setAttributeInternal(PRODPERLINEPERH, value);
    }

    /**
     * Gets the attribute value for STYLE_EFFICIENCY using the alias name StyleEfficiency.
     * @return the STYLE_EFFICIENCY
     */
    public Number getStyleEfficiency() {
        return (Number) getAttributeInternal(STYLEEFFICIENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_EFFICIENCY using the alias name StyleEfficiency.
     * @param value value to set the STYLE_EFFICIENCY
     */
    public void setStyleEfficiency(Number value) {
        setAttributeInternal(STYLEEFFICIENCY, value);
    }

    /**
     * Gets the attribute value for SAM using the alias name Sam.
     * @return the SAM
     */
    public Number getSam() {
        return (Number) getAttributeInternal(SAM);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM using the alias name Sam.
     * @param value value to set the SAM
     */
    public void setSam(Number value) {
        setAttributeInternal(SAM, value);
    }

    /**
     * Gets the attribute value for SMV using the alias name Smv.
     * @return the SMV
     */
    public String getSmv() {
        return (String) getAttributeInternal(SMV);
    }

    /**
     * Sets <code>value</code> as attribute value for SMV using the alias name Smv.
     * @param value value to set the SMV
     */
    public void setSmv(String value) {
        setAttributeInternal(SMV, value);
    }

    /**
     * Gets the attribute value for FACTORY_AVG_EF using the alias name FactoryAvgEf.
     * @return the FACTORY_AVG_EF
     */
    public String getFactoryAvgEf() {
        return (String) getAttributeInternal(FACTORYAVGEF);
    }

    /**
     * Sets <code>value</code> as attribute value for FACTORY_AVG_EF using the alias name FactoryAvgEf.
     * @param value value to set the FACTORY_AVG_EF
     */
    public void setFactoryAvgEf(String value) {
        setAttributeInternal(FACTORYAVGEF, value);
    }

    /**
     * Gets the attribute value for PROD_COST_LINE_PER_H using the alias name ProdCostLinePerH.
     * @return the PROD_COST_LINE_PER_H
     */
    public Number getProdCostLinePerH() {
        return (Number) getAttributeInternal(PRODCOSTLINEPERH);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_COST_LINE_PER_H using the alias name ProdCostLinePerH.
     * @param value value to set the PROD_COST_LINE_PER_H
     */
    public void setProdCostLinePerH(Number value) {
        setAttributeInternal(PRODCOSTLINEPERH, value);
    }

    /**
     * Gets the attribute value for COST_NEW using the alias name CostNew.
     * @return the COST_NEW
     */
    public Number getCostNew() {
        return (Number) getAttributeInternal(COSTNEW);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_NEW using the alias name CostNew.
     * @param value value to set the COST_NEW
     */
    public void setCostNew(Number value) {
        setAttributeInternal(COSTNEW, value);
    }

    /**
     * Gets the attribute value for FINAL_FINISH_GOODS_COLOUR using the alias name FinalFinishGoodsColour.
     * @return the FINAL_FINISH_GOODS_COLOUR
     */
    public String getFinalFinishGoodsColour() {
        return (String) getAttributeInternal(FINALFINISHGOODSCOLOUR);
    }

    /**
     * Sets <code>value</code> as attribute value for FINAL_FINISH_GOODS_COLOUR using the alias name FinalFinishGoodsColour.
     * @param value value to set the FINAL_FINISH_GOODS_COLOUR
     */
    public void setFinalFinishGoodsColour(String value) {
        setAttributeInternal(FINALFINISHGOODSCOLOUR, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for FABRIC_CONTENT using the alias name FabricContent.
     * @return the FABRIC_CONTENT
     */
    public String getFabricContent() {
        return (String) getAttributeInternal(FABRICCONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_CONTENT using the alias name FabricContent.
     * @param value value to set the FABRIC_CONTENT
     */
    public void setFabricContent(String value) {
        setAttributeInternal(FABRICCONTENT, value);
    }

    /**
     * Gets the attribute value for COMMISON_PRCNT using the alias name CommisonPrcnt1.
     * @return the COMMISON_PRCNT
     */
  

    /**
     * Sets <code>value</code> as attribute value for COMMISON_PRCNT using the alias name CommisonPrcnt1.
     * @param value value to set the COMMISON_PRCNT
     */


    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for DELIVERY_END_DATE using the alias name DeliveryEndDate.
     * @return the DELIVERY_END_DATE
     */
    public Date getDeliveryEndDate() {
        return (Date) getAttributeInternal(DELIVERYENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_END_DATE using the alias name DeliveryEndDate.
     * @param value value to set the DELIVERY_END_DATE
     */
    public void setDeliveryEndDate(Date value) {
        setAttributeInternal(DELIVERYENDDATE, value);
    }

    /**
     * Gets the attribute value for DELIVERY_START_DATE using the alias name DeliveryStartDate.
     * @return the DELIVERY_START_DATE
     */
    public Date getDeliveryStartDate() {
        return (Date) getAttributeInternal(DELIVERYSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_START_DATE using the alias name DeliveryStartDate.
     * @param value value to set the DELIVERY_START_DATE
     */
    public void setDeliveryStartDate(Date value) {
        setAttributeInternal(DELIVERYSTARTDATE, value);
    }

    /**
     * Gets the attribute value for REPLACE_WASH using the alias name ReplaceWash.
     * @return the REPLACE_WASH
     */
    public String getReplaceWash() {
        return (String) getAttributeInternal(REPLACEWASH);
    }

    /**
     * Sets <code>value</code> as attribute value for REPLACE_WASH using the alias name ReplaceWash.
     * @param value value to set the REPLACE_WASH
     */
    public void setReplaceWash(String value) {
        setAttributeInternal(REPLACEWASH, value);
    }


    /**
     * Gets the attribute value for REPLACE_BPO using the alias name ReplaceBpo.
     * @return the REPLACE_BPO
     */
    public String getReplaceBpo() {
        return (String) getAttributeInternal(REPLACEBPO);
    }

    /**
     * Sets <code>value</code> as attribute value for REPLACE_BPO using the alias name ReplaceBpo.
     * @param value value to set the REPLACE_BPO
     */
    public void setReplaceBpo(String value) {
        setAttributeInternal(REPLACEBPO, value);
    }

    /**
     * Gets the attribute value for SHIP_MODE using the alias name ShipMode.
     * @return the SHIP_MODE
     */
    public String getShipMode() {
        return (String) getAttributeInternal(SHIPMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_MODE using the alias name ShipMode.
     * @param value value to set the SHIP_MODE
     */
    public void setShipMode(String value) {
        setAttributeInternal(SHIPMODE, value);
    }

    /**
     * Gets the attribute value for OTHER_CHARGE using the alias name OtherCharge.
     * @return the OTHER_CHARGE
     */
    public Number getOtherCharge() {
        return (Number) getAttributeInternal(OTHERCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_CHARGE using the alias name OtherCharge.
     * @param value value to set the OTHER_CHARGE
     */
    public void setOtherCharge(Number value) {
        setAttributeInternal(OTHERCHARGE, value);
    }

    /**
     * Gets the attribute value for LAB_TEST_CHARGE using the alias name LabTestCharge.
     * @return the LAB_TEST_CHARGE
     */
    public Number getLabTestCharge() {
        return (Number) getAttributeInternal(LABTESTCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAB_TEST_CHARGE using the alias name LabTestCharge.
     * @param value value to set the LAB_TEST_CHARGE
     */
    public void setLabTestCharge(Number value) {
        setAttributeInternal(LABTESTCHARGE, value);
    }

    /**
     * Gets the attribute value for PRINT using the alias name Print.
     * @return the PRINT
     */
    public Number getPrint() {
        return (Number) getAttributeInternal(PRINT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRINT using the alias name Print.
     * @param value value to set the PRINT
     */
    public void setPrint(Number value) {
        setAttributeInternal(PRINT, value);
    }

    /**
     * Gets the attribute value for FABRIC_FINANCE using the alias name FabricFinance.
     * @return the FABRIC_FINANCE
     */
    public Number getFabricFinance() {
        return (Number) getAttributeInternal(FABRICFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_FINANCE using the alias name FabricFinance.
     * @param value value to set the FABRIC_FINANCE
     */
    public void setFabricFinance(Number value) {
        setAttributeInternal(FABRICFINANCE, value);
    }

    /**
     * Gets the attribute value for WASH_FINANCE using the alias name WashFinance.
     * @return the WASH_FINANCE
     */
    public Number getWashFinance() {
        return (Number) getAttributeInternal(WASHFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_FINANCE using the alias name WashFinance.
     * @param value value to set the WASH_FINANCE
     */
    public void setWashFinance(Number value) {
        setAttributeInternal(WASHFINANCE, value);
    }

    /**
     * Gets the attribute value for TRIM_FINANCE using the alias name TrimFinance.
     * @return the TRIM_FINANCE
     */
    public Number getTrimFinance() {
        return (Number) getAttributeInternal(TRIMFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIM_FINANCE using the alias name TrimFinance.
     * @param value value to set the TRIM_FINANCE
     */
    public void setTrimFinance(Number value) {
        setAttributeInternal(TRIMFINANCE, value);
    }

    /**
     * Gets the attribute value for COMMISON_PRCNT using the alias name CommisonPrcnt.
     * @return the COMMISON_PRCNT
     */
    public Number getCommisonPrcnt() {
        return (Number) getAttributeInternal(COMMISONPRCNT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISON_PRCNT using the alias name CommisonPrcnt.
     * @param value value to set the COMMISON_PRCNT
     */
    public void setCommisonPrcnt(Number value) {
        setAttributeInternal(COMMISONPRCNT, value);
    }

    /**
     * Gets the attribute value for SMS_QTY using the alias name SmsQty.
     * @return the SMS_QTY
     */
    public Number getSmsQty() {
        return (Number) getAttributeInternal(SMSQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SMS_QTY using the alias name SmsQty.
     * @param value value to set the SMS_QTY
     */
    public void setSmsQty(Number value) {
        setAttributeInternal(SMSQTY, value);
    }

    /**
     * Gets the attribute value for FABRIC_DESC using the alias name FabricDesc.
     * @return the FABRIC_DESC
     */
    public String getFabricDesc() {
        return (String) getAttributeInternal(FABRICDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_DESC using the alias name FabricDesc.
     * @param value value to set the FABRIC_DESC
     */
    public void setFabricDesc(String value) {
        setAttributeInternal(FABRICDESC, value);
    }

    /**
     * Gets the attribute value for CLONE_FLAG using the alias name CloneFlag.
     * @return the CLONE_FLAG
     */
    public String getCloneFlag() {
        return (String) getAttributeInternal(CLONEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CLONE_FLAG using the alias name CloneFlag.
     * @param value value to set the CLONE_FLAG
     */
    public void setCloneFlag(String value) {
        setAttributeInternal(CLONEFLAG, value);
    }

    /**
     * Gets the attribute value for FOB using the alias name Fob.
     * @return the FOB
     */
    public Number getFob() {
        return (Number) getAttributeInternal(FOB);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB using the alias name Fob.
     * @param value value to set the FOB
     */
    public void setFob(Number value) {
        setAttributeInternal(FOB, value);
    }

    /**
     * Gets the attribute value for FABRIC_COST using the alias name FabricCost.
     * @return the FABRIC_COST
     */
    public Number getFabricCost() {
        return (Number) getAttributeInternal(FABRICCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_COST using the alias name FabricCost.
     * @param value value to set the FABRIC_COST
     */
    public void setFabricCost(Number value) {
        setAttributeInternal(FABRICCOST, value);
    }

    /**
     * Gets the attribute value for TRIM_COST using the alias name TrimCost.
     * @return the TRIM_COST
     */
    public Number getTrimCost() {
        return (Number) getAttributeInternal(TRIMCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIM_COST using the alias name TrimCost.
     * @param value value to set the TRIM_COST
     */
    public void setTrimCost(Number value) {
        setAttributeInternal(TRIMCOST, value);
    }

    /**
     * Gets the attribute value for WASH_COST using the alias name WashCost.
     * @return the WASH_COST
     */
    public Number getWashCost() {
        return (Number) getAttributeInternal(WASHCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_COST using the alias name WashCost.
     * @param value value to set the WASH_COST
     */
    public void setWashCost(Number value) {
        setAttributeInternal(WASHCOST, value);
    }

    /**
     * Gets the attribute value for TARGET_PRICE using the alias name TargetPrice.
     * @return the TARGET_PRICE
     */
    public Number getTargetPrice() {
        return (Number) getAttributeInternal(TARGETPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_PRICE using the alias name TargetPrice.
     * @param value value to set the TARGET_PRICE
     */
    public void setTargetPrice(Number value) {
        setAttributeInternal(TARGETPRICE, value);
    }

    /**
     * Gets the attribute value for DIFFERENCE using the alias name Difference.
     * @return the DIFFERENCE
     */
    public Number getDifference() {
        return (Number) getAttributeInternal(DIFFERENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for DIFFERENCE using the alias name Difference.
     * @param value value to set the DIFFERENCE
     */
    public void setDifference(Number value) {
        setAttributeInternal(DIFFERENCE, value);
    }

    /**
     * Gets the attribute value for OTHERS using the alias name Others.
     * @return the OTHERS
     */
    public Number getOthers() {
        return (Number) getAttributeInternal(OTHERS);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHERS using the alias name Others.
     * @param value value to set the OTHERS
     */
    public void setOthers(Number value) {
        setAttributeInternal(OTHERS, value);
    }


    /**
     * Gets the attribute value for CHILD_STYLE_NO using the alias name ChildStyleNo.
     * @return the CHILD_STYLE_NO
     */
    public String getChildStyleNo() {
        return (String) getAttributeInternal(CHILDSTYLENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CHILD_STYLE_NO using the alias name ChildStyleNo.
     * @param value value to set the CHILD_STYLE_NO
     */
    public void setChildStyleNo(String value) {
        setAttributeInternal(CHILDSTYLENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Weight.
     * @return the Weight
     */
    public String getWeight() {
        return (String) getAttributeInternal(WEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Weight.
     * @param value value to set the  Weight
     */
    public void setWeight(String value) {
        setAttributeInternal(WEIGHT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WeightType.
     * @return the WeightType
     */
    public String getWeightType() {
        return (String) getAttributeInternal(WEIGHTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WeightType.
     * @param value value to set the  WeightType
     */
    public void setWeightType(String value) {
        setAttributeInternal(WEIGHTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WidthType.
     * @return the WidthType
     */
    public String getWidthType() {
        return (String) getAttributeInternal(WIDTHTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WidthType.
     * @param value value to set the  WidthType
     */
    public void setWidthType(String value) {
        setAttributeInternal(WIDTHTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WidthValue.
     * @return the WidthValue
     */
    public Number getWidthValue() {
        return (Number) getAttributeInternal(WIDTHVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WidthValue.
     * @param value value to set the  WidthValue
     */
    public void setWidthValue(Number value) {
        setAttributeInternal(WIDTHVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FabricFinsih.
     * @return the FabricFinsih
     */
    public String getFabricFinsih() {
        return (String) getAttributeInternal(FABRICFINSIH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FabricFinsih.
     * @param value value to set the  FabricFinsih
     */
    public void setFabricFinsih(String value) {
        setAttributeInternal(FABRICFINSIH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Elongation.
     * @return the Elongation
     */
    public String getElongation() {
        return (String) getAttributeInternal(ELONGATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Elongation.
     * @param value value to set the  Elongation
     */
    public void setElongation(String value) {
        setAttributeInternal(ELONGATION, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgPrecostingItemDView.
     */
    public RowIterator getMnjMfgPrecostingItemDView() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGITEMDVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgPrecostingCountryDView.
     */
    public RowIterator getMnjMfgPrecostingCountryDView() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGCOUNTRYDVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgPrecostingWetDView.
     */
    public RowIterator getMnjMfgPrecostingWetDView() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGWETDVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DryDetailVO.
     */
    public RowIterator getDryDetailVO() {
        return (RowIterator)getAttributeInternal(DRYDETAILVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UpdateOrderInterface.
     */
    public RowIterator getUpdateOrderInterface() {
        return (RowIterator)getAttributeInternal(UPDATEORDERINTERFACE);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link MnjMfgPrecostingHView.
     */
    public Row getMnjMfgPrecostingHView() {
        return (Row)getAttributeInternal(MNJMFGPRECOSTINGHVIEW);
    }

    /**
     * Sets the master-detail link MnjMfgPrecostingHView between this object and <code>value</code>.
     */
    public void setMnjMfgPrecostingHView(Row value) {
        setAttributeInternal(MNJMFGPRECOSTINGHVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ColorLOv1.
     */
    public RowSet getColorLOv1() {
        return (RowSet)getAttributeInternal(COLORLOV1);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
