package mnj.mfg.model.views;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import mnj.mfg.model.views.common.MnjMfgPrecostingHView;

import oracle.jbo.ViewLink;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 14 19:42:25 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingHViewImpl extends ViewObjectImpl implements MnjMfgPrecostingHView {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingHViewImpl() {
    }

    /**
     * Returns the variable value for p_precostingNo.
     * @return variable value for p_precostingNo
     */
    public String getp_precostingNo() {
        return (String)ensureVariableManager().getVariableValue("p_precostingNo");
    }
    public void setURLParam(String userId, String orgId, String respId,
                            String respApplId) {
                            }
    /**
     * Sets <code>value</code> for variable p_precostingNo.
     * @param value value to bind as p_precostingNo
     */
    public void setp_precostingNo(String value) {
        ensureVariableManager().setVariableValue("p_precostingNo", value);
    }

   

    public void openSpecificPOC(String POC) {

        if (POC != null) {
            this.setWhereClause("HEADER_NO =" + POC);
            this.executeQuery();
             
        }

    }

    /**
     * Returns the bind variable value for p_userId.
     * @return bind variable value for p_userId
     */
    public String getp_userId() {
        return (String)getNamedWhereClauseParam("p_userId");
    }

    /**
     * Sets <code>value</code> for bind variable p_userId.
     * @param value value to bind as p_userId
     */
    public void setp_userId(String value) {
        setNamedWhereClauseParam("p_userId", value);
    }
}
