package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgPrecostingItemDImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 05 17:36:14 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingItemDViewRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingItemDViewRowImpl() {
    }

    /**
     * Gets MnjMfgPrecostingItemD entity object.
     * @return the MnjMfgPrecostingItemD
     */
    public MnjMfgPrecostingItemDImpl getMnjMfgPrecostingItemD() {
        return (MnjMfgPrecostingItemDImpl)getEntity(0);
    }
}
