package mnj.mfg.model.views;

import mnj.mfg.model.views.common.MnjMfgPrecostingLView;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 06 21:07:56 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingLViewImpl extends ViewObjectImpl implements MnjMfgPrecostingLView {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingLViewImpl() {
    }

    @Override
    public void insertRow(Row row) {

        Row lastRow = this.last();
        if (lastRow != null) {
            //insert new row at the end and make it current
            int indx = this.getRangeIndexOf(lastRow) + 1;
            this.insertRowAtRangeIndex(indx, row);
            this.setCurrentRow(row);
        } else { // empty Rowset
            super.insertRow(row);
        }
    }
    
    public void ExecuteLines(String POC){
        
        if(POC != null){
//            this.setNamedWhereClauseParam("Bind_HeaderId", "39");
//            this.executeQuery();
            System.out.println(this.getQuery()); 
            
        }
    }


}
