package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgPrecostingHImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 18 15:42:44 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingHViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        HeaderNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getHeaderNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setHeaderNo((String)value);
            }
        }
        ,
        OrderProjectionNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getOrderProjectionNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setOrderProjectionNo((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        DropPeriod {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getDropPeriod();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setDropPeriod((String)value);
            }
        }
        ,
        Brand {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getBrand();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        StyleName {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getStyleName();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        CurrentStyleName {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCurrentStyleName();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCurrentStyleName((String)value);
            }
        }
        ,
        StyleNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getStyleNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setStyleNo((String)value);
            }
        }
        ,
        CurrentStyleNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCurrentStyleNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCurrentStyleNo((String)value);
            }
        }
        ,
        ConditionalProdStyleNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getConditionalProdStyleNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setConditionalProdStyleNo((String)value);
            }
        }
        ,
        Fit {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getFit();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setFit((String)value);
            }
        }
        ,
        EndUser {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getEndUser();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setEndUser((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        ColourWash {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getColourWash();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setColourWash((String)value);
            }
        }
        ,
        OtherCharges {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getOtherCharges();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setOtherCharges((Number)value);
            }
        }
        ,
        LabTestCharges {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getLabTestCharges();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setLabTestCharges((Number)value);
            }
        }
        ,
        Print {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getPrint();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setPrint((Number)value);
            }
        }
        ,
        Commission {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCommission();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCommission((Number)value);
            }
        }
        ,
        SmsQty {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getSmsQty();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setSmsQty((Number)value);
            }
        }
        ,
        OrderQty {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        CostingMou {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCostingMou();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCostingMou((String)value);
            }
        }
        ,
        FabricFinance {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getFabricFinance();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setFabricFinance((Number)value);
            }
        }
        ,
        TrimFinance {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getTrimFinance();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setTrimFinance((Number)value);
            }
        }
        ,
        WashFinance {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getWashFinance();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setWashFinance((Number)value);
            }
        }
        ,
        ProductionUnit {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getProductionUnit();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setProductionUnit((String)value);
            }
        }
        ,
        CmMerchandiser {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCmMerchandiser();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCmMerchandiser((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        ProdPerLinePerH {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getProdPerLinePerH();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setProdPerLinePerH((Number)value);
            }
        }
        ,
        Season {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        TransferStatus {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getTransferStatus();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setTransferStatus((String)value);
            }
        }
        ,
        Status {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        GmApproval {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getGmApproval();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setGmApproval((String)value);
            }
        }
        ,
        MdApproval {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getMdApproval();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setMdApproval((String)value);
            }
        }
        ,
        CmMerchandiserD {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCmMerchandiserD();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCmMerchandiserD((String)value);
            }
        }
        ,
        AgencyCommission {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getAgencyCommission();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAgencyCommission((String)value);
            }
        }
        ,
        Buyer {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getBuyer();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        BuyerCriteria {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getBuyerCriteria();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setBuyerCriteria((String)value);
            }
        }
        ,
        GmStatus {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getGmStatus();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setGmStatus((String)value);
            }
        }
        ,
        MdStatus {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getMdStatus();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setMdStatus((String)value);
            }
        }
        ,
        SampleDocNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getSampleDocNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setSampleDocNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        VersionNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getVersionNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        PocType {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getPocType();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setPocType((String)value);
            }
        }
        ,
        ProdStyleNo {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getProdStyleNo();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setProdStyleNo((String)value);
            }
        }
        ,
        ProdCostLinePerH {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getProdCostLinePerH();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setProdCostLinePerH((Number)value);
            }
        }
        ,
        BpoQty {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getBpoQty();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setBpoQty((String)value);
            }
        }
        ,
        TotalBpoTbaQty {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getTotalBpoTbaQty();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setTotalBpoTbaQty((String)value);
            }
        }
        ,
        CmCalculation {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCmCalculation();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setCmCalculation((String)value);
            }
        }
        ,
        Attachemnt {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getAttachemnt();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttachemnt((Number)value);
            }
        }
        ,
        Division {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getDivision();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        ItemPurchaseType {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getItemPurchaseType();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setItemPurchaseType((String)value);
            }
        }
        ,
        StyleTracking {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getStyleTracking();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setStyleTracking((String)value);
            }
        }
        ,
        StyleNameNew {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getStyleNameNew();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setStyleNameNew((String)value);
            }
        }
        ,
        MnjMfgPrecostingLView {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getMnjMfgPrecostingLView();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreateSaleOrderLinesVO {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCreateSaleOrderLinesVO();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdateOrderInterface {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getUpdateOrderInterface();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrderProjectionVO1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getOrderProjectionVO1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OperatingUnits1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getOperatingUnits1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getBuyerLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SeasonLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getSeasonLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        brandLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getbrandLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FitLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getFitLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EndUserLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getEndUserLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EndUserLov2 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getEndUserLov2();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemDescLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getItemDescLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CostingUOMLov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getCostingUOMLov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PocTypeVO1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getPocTypeVO1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DivisionTracking1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getDivisionTracking1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Style_division_tracking_lov1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getStyle_division_tracking_lov1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemPurchaseTypeLOV1 {
            public Object get(MnjMfgPrecostingHViewRowImpl obj) {
                return obj.getItemPurchaseTypeLOV1();
            }

            public void put(MnjMfgPrecostingHViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgPrecostingHViewRowImpl object);

        public abstract void put(MnjMfgPrecostingHViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int HEADERNO = AttributesEnum.HeaderNo.index();
    public static final int ORDERPROJECTIONNO = AttributesEnum.OrderProjectionNo.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int DROPPERIOD = AttributesEnum.DropPeriod.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int CURRENTSTYLENAME = AttributesEnum.CurrentStyleName.index();
    public static final int STYLENO = AttributesEnum.StyleNo.index();
    public static final int CURRENTSTYLENO = AttributesEnum.CurrentStyleNo.index();
    public static final int CONDITIONALPRODSTYLENO = AttributesEnum.ConditionalProdStyleNo.index();
    public static final int FIT = AttributesEnum.Fit.index();
    public static final int ENDUSER = AttributesEnum.EndUser.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int COLOURWASH = AttributesEnum.ColourWash.index();
    public static final int OTHERCHARGES = AttributesEnum.OtherCharges.index();
    public static final int LABTESTCHARGES = AttributesEnum.LabTestCharges.index();
    public static final int PRINT = AttributesEnum.Print.index();
    public static final int COMMISSION = AttributesEnum.Commission.index();
    public static final int SMSQTY = AttributesEnum.SmsQty.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int COSTINGMOU = AttributesEnum.CostingMou.index();
    public static final int FABRICFINANCE = AttributesEnum.FabricFinance.index();
    public static final int TRIMFINANCE = AttributesEnum.TrimFinance.index();
    public static final int WASHFINANCE = AttributesEnum.WashFinance.index();
    public static final int PRODUCTIONUNIT = AttributesEnum.ProductionUnit.index();
    public static final int CMMERCHANDISER = AttributesEnum.CmMerchandiser.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int PRODPERLINEPERH = AttributesEnum.ProdPerLinePerH.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int TRANSFERSTATUS = AttributesEnum.TransferStatus.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int GMAPPROVAL = AttributesEnum.GmApproval.index();
    public static final int MDAPPROVAL = AttributesEnum.MdApproval.index();
    public static final int CMMERCHANDISERD = AttributesEnum.CmMerchandiserD.index();
    public static final int AGENCYCOMMISSION = AttributesEnum.AgencyCommission.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int BUYERCRITERIA = AttributesEnum.BuyerCriteria.index();
    public static final int GMSTATUS = AttributesEnum.GmStatus.index();
    public static final int MDSTATUS = AttributesEnum.MdStatus.index();
    public static final int SAMPLEDOCNO = AttributesEnum.SampleDocNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int POCTYPE = AttributesEnum.PocType.index();
    public static final int PRODSTYLENO = AttributesEnum.ProdStyleNo.index();
    public static final int PRODCOSTLINEPERH = AttributesEnum.ProdCostLinePerH.index();
    public static final int BPOQTY = AttributesEnum.BpoQty.index();
    public static final int TOTALBPOTBAQTY = AttributesEnum.TotalBpoTbaQty.index();
    public static final int CMCALCULATION = AttributesEnum.CmCalculation.index();
    public static final int ATTACHEMNT = AttributesEnum.Attachemnt.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int ITEMPURCHASETYPE = AttributesEnum.ItemPurchaseType.index();
    public static final int STYLETRACKING = AttributesEnum.StyleTracking.index();
    public static final int STYLENAMENEW = AttributesEnum.StyleNameNew.index();
    public static final int MNJMFGPRECOSTINGLVIEW = AttributesEnum.MnjMfgPrecostingLView.index();
    public static final int CREATESALEORDERLINESVO = AttributesEnum.CreateSaleOrderLinesVO.index();
    public static final int UPDATEORDERINTERFACE = AttributesEnum.UpdateOrderInterface.index();
    public static final int ORDERPROJECTIONVO1 = AttributesEnum.OrderProjectionVO1.index();
    public static final int OPERATINGUNITS1 = AttributesEnum.OperatingUnits1.index();
    public static final int BUYERLOV1 = AttributesEnum.BuyerLov1.index();
    public static final int SEASONLOV1 = AttributesEnum.SeasonLov1.index();
    public static final int BRANDLOV1 = AttributesEnum.brandLov1.index();
    public static final int FITLOV1 = AttributesEnum.FitLov1.index();
    public static final int ENDUSERLOV1 = AttributesEnum.EndUserLov1.index();
    public static final int ENDUSERLOV2 = AttributesEnum.EndUserLov2.index();
    public static final int ITEMDESCLOV1 = AttributesEnum.ItemDescLov1.index();
    public static final int COSTINGUOMLOV1 = AttributesEnum.CostingUOMLov1.index();
    public static final int POCTYPEVO1 = AttributesEnum.PocTypeVO1.index();
    public static final int DIVISIONTRACKING1 = AttributesEnum.DivisionTracking1.index();
    public static final int STYLE_DIVISION_TRACKING_LOV1 = AttributesEnum.Style_division_tracking_lov1.index();
    public static final int ITEMPURCHASETYPELOV1 = AttributesEnum.ItemPurchaseTypeLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingHViewRowImpl() {
    }

    /**
     * Gets MnjMfgPrecostingH entity object.
     * @return the MnjMfgPrecostingH
     */
    public MnjMfgPrecostingHImpl getMnjMfgPrecostingH() {
        return (MnjMfgPrecostingHImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for HEADER_NO using the alias name HeaderNo.
     * @return the HEADER_NO
     */
    public String getHeaderNo() {
        return (String) getAttributeInternal(HEADERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_NO using the alias name HeaderNo.
     * @param value value to set the HEADER_NO
     */
    public void setHeaderNo(String value) {
        setAttributeInternal(HEADERNO, value);
    }

    /**
     * Gets the attribute value for ORDER_PROJECTION_NO using the alias name OrderProjectionNo.
     * @return the ORDER_PROJECTION_NO
     */
    public Number getOrderProjectionNo() {
        return (Number) getAttributeInternal(ORDERPROJECTIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_PROJECTION_NO using the alias name OrderProjectionNo.
     * @param value value to set the ORDER_PROJECTION_NO
     */
    public void setOrderProjectionNo(Number value) {
        setAttributeInternal(ORDERPROJECTIONNO, value);
    }

    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for DROP_PERIOD using the alias name DropPeriod.
     * @return the DROP_PERIOD
     */
    public String getDropPeriod() {
        return (String) getAttributeInternal(DROPPERIOD);
    }

    /**
     * Sets <code>value</code> as attribute value for DROP_PERIOD using the alias name DropPeriod.
     * @param value value to set the DROP_PERIOD
     */
    public void setDropPeriod(String value) {
        setAttributeInternal(DROPPERIOD, value);
    }

    /**
     * Gets the attribute value for BRAND using the alias name Brand.
     * @return the BRAND
     */
    public String getBrand() {
        return (String) getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as attribute value for BRAND using the alias name Brand.
     * @param value value to set the BRAND
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for STYLE_NAME using the alias name StyleName.
     * @return the STYLE_NAME
     */
    public String getStyleName() {
        return (String) getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NAME using the alias name StyleName.
     * @param value value to set the STYLE_NAME
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyleName.
     * @return the CurrentStyleName
     */
    public String getCurrentStyleName() {
        return (String) getAttributeInternal(CURRENTSTYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyleName.
     * @param value value to set the  CurrentStyleName
     */
    public void setCurrentStyleName(String value) {
        setAttributeInternal(CURRENTSTYLENAME, value);
    }

    /**
     * Gets the attribute value for STYLE_NO using the alias name StyleNo.
     * @return the STYLE_NO
     */
    public String getStyleNo() {
        return (String) getAttributeInternal(STYLENO);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NO using the alias name StyleNo.
     * @param value value to set the STYLE_NO
     */
    public void setStyleNo(String value) {
        setAttributeInternal(STYLENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyleNo.
     * @return the CurrentStyleNo
     */
    public String getCurrentStyleNo() {
        return (String) getAttributeInternal(CURRENTSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyleNo.
     * @param value value to set the  CurrentStyleNo
     */
    public void setCurrentStyleNo(String value) {
        setAttributeInternal(CURRENTSTYLENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ConditionalProdStyleNo.
     * @return the ConditionalProdStyleNo
     */
    public String getConditionalProdStyleNo() {
        return (String) getAttributeInternal(CONDITIONALPRODSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConditionalProdStyleNo.
     * @param value value to set the  ConditionalProdStyleNo
     */
    public void setConditionalProdStyleNo(String value) {
        setAttributeInternal(CONDITIONALPRODSTYLENO, value);
    }

    /**
     * Gets the attribute value for FIT using the alias name Fit.
     * @return the FIT
     */
    public String getFit() {
        return (String) getAttributeInternal(FIT);
    }

    /**
     * Sets <code>value</code> as attribute value for FIT using the alias name Fit.
     * @param value value to set the FIT
     */
    public void setFit(String value) {
        setAttributeInternal(FIT, value);
    }

    /**
     * Gets the attribute value for END_USER using the alias name EndUser.
     * @return the END_USER
     */
    public String getEndUser() {
        return (String) getAttributeInternal(ENDUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for END_USER using the alias name EndUser.
     * @param value value to set the END_USER
     */
    public void setEndUser(String value) {
        setAttributeInternal(ENDUSER, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for COLOUR_WASH using the alias name ColourWash.
     * @return the COLOUR_WASH
     */
    public String getColourWash() {
        return (String) getAttributeInternal(COLOURWASH);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOUR_WASH using the alias name ColourWash.
     * @param value value to set the COLOUR_WASH
     */
    public void setColourWash(String value) {
        setAttributeInternal(COLOURWASH, value);
    }

    /**
     * Gets the attribute value for OTHER_CHARGES using the alias name OtherCharges.
     * @return the OTHER_CHARGES
     */
    public Number getOtherCharges() {
        return (Number) getAttributeInternal(OTHERCHARGES);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_CHARGES using the alias name OtherCharges.
     * @param value value to set the OTHER_CHARGES
     */
    public void setOtherCharges(Number value) {
        setAttributeInternal(OTHERCHARGES, value);
    }

    /**
     * Gets the attribute value for LAB_TEST_CHARGES using the alias name LabTestCharges.
     * @return the LAB_TEST_CHARGES
     */
    public Number getLabTestCharges() {
        return (Number) getAttributeInternal(LABTESTCHARGES);
    }

    /**
     * Sets <code>value</code> as attribute value for LAB_TEST_CHARGES using the alias name LabTestCharges.
     * @param value value to set the LAB_TEST_CHARGES
     */
    public void setLabTestCharges(Number value) {
        setAttributeInternal(LABTESTCHARGES, value);
    }

    /**
     * Gets the attribute value for PRINT using the alias name Print.
     * @return the PRINT
     */
    public Number getPrint() {
        return (Number) getAttributeInternal(PRINT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRINT using the alias name Print.
     * @param value value to set the PRINT
     */
    public void setPrint(Number value) {
        setAttributeInternal(PRINT, value);
    }

    /**
     * Gets the attribute value for COMMISSION using the alias name Commission.
     * @return the COMMISSION
     */
    public Number getCommission() {
        return (Number) getAttributeInternal(COMMISSION);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISSION using the alias name Commission.
     * @param value value to set the COMMISSION
     */
    public void setCommission(Number value) {
        setAttributeInternal(COMMISSION, value);
    }

    /**
     * Gets the attribute value for SMS_QTY using the alias name SmsQty.
     * @return the SMS_QTY
     */
    public Number getSmsQty() {
        return (Number) getAttributeInternal(SMSQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SMS_QTY using the alias name SmsQty.
     * @param value value to set the SMS_QTY
     */
    public void setSmsQty(Number value) {
        setAttributeInternal(SMSQTY, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for COSTING_MOU using the alias name CostingMou.
     * @return the COSTING_MOU
     */
    public String getCostingMou() {
        return (String) getAttributeInternal(COSTINGMOU);
    }

    /**
     * Sets <code>value</code> as attribute value for COSTING_MOU using the alias name CostingMou.
     * @param value value to set the COSTING_MOU
     */
    public void setCostingMou(String value) {
        setAttributeInternal(COSTINGMOU, value);
    }

    /**
     * Gets the attribute value for FABRIC_FINANCE using the alias name FabricFinance.
     * @return the FABRIC_FINANCE
     */
    public Number getFabricFinance() {
        return (Number) getAttributeInternal(FABRICFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_FINANCE using the alias name FabricFinance.
     * @param value value to set the FABRIC_FINANCE
     */
    public void setFabricFinance(Number value) {
        setAttributeInternal(FABRICFINANCE, value);
    }

    /**
     * Gets the attribute value for TRIM_FINANCE using the alias name TrimFinance.
     * @return the TRIM_FINANCE
     */
    public Number getTrimFinance() {
        return (Number) getAttributeInternal(TRIMFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIM_FINANCE using the alias name TrimFinance.
     * @param value value to set the TRIM_FINANCE
     */
    public void setTrimFinance(Number value) {
        setAttributeInternal(TRIMFINANCE, value);
    }

    /**
     * Gets the attribute value for WASH_FINANCE using the alias name WashFinance.
     * @return the WASH_FINANCE
     */
    public Number getWashFinance() {
        return (Number) getAttributeInternal(WASHFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_FINANCE using the alias name WashFinance.
     * @param value value to set the WASH_FINANCE
     */
    public void setWashFinance(Number value) {
        setAttributeInternal(WASHFINANCE, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_UNIT using the alias name ProductionUnit.
     * @return the PRODUCTION_UNIT
     */
    public String getProductionUnit() {
        return (String) getAttributeInternal(PRODUCTIONUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_UNIT using the alias name ProductionUnit.
     * @param value value to set the PRODUCTION_UNIT
     */
    public void setProductionUnit(String value) {
        setAttributeInternal(PRODUCTIONUNIT, value);
    }

    /**
     * Gets the attribute value for CM_MERCHANDISER using the alias name CmMerchandiser.
     * @return the CM_MERCHANDISER
     */
    public String getCmMerchandiser() {
        return (String) getAttributeInternal(CMMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MERCHANDISER using the alias name CmMerchandiser.
     * @param value value to set the CM_MERCHANDISER
     */
    public void setCmMerchandiser(String value) {
        setAttributeInternal(CMMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for PROD_PER_LINE_PER_H using the alias name ProdPerLinePerH.
     * @return the PROD_PER_LINE_PER_H
     */
    public Number getProdPerLinePerH() {
        return (Number) getAttributeInternal(PRODPERLINEPERH);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_PER_LINE_PER_H using the alias name ProdPerLinePerH.
     * @param value value to set the PROD_PER_LINE_PER_H
     */
    public void setProdPerLinePerH(Number value) {
        setAttributeInternal(PRODPERLINEPERH, value);
    }

    /**
     * Gets the attribute value for SEASON using the alias name Season.
     * @return the SEASON
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON using the alias name Season.
     * @param value value to set the SEASON
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for GM_APPROVAL using the alias name GmApproval.
     * @return the GM_APPROVAL
     */
    public String getGmApproval() {
        return (String) getAttributeInternal(GMAPPROVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for GM_APPROVAL using the alias name GmApproval.
     * @param value value to set the GM_APPROVAL
     */
    public void setGmApproval(String value) {
        setAttributeInternal(GMAPPROVAL, value);
    }

    /**
     * Gets the attribute value for MD_APPROVAL using the alias name MdApproval.
     * @return the MD_APPROVAL
     */
    public String getMdApproval() {
        return (String) getAttributeInternal(MDAPPROVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for MD_APPROVAL using the alias name MdApproval.
     * @param value value to set the MD_APPROVAL
     */
    public void setMdApproval(String value) {
        setAttributeInternal(MDAPPROVAL, value);
    }

    /**
     * Gets the attribute value for CM_MERCHANDISER_D using the alias name CmMerchandiserD.
     * @return the CM_MERCHANDISER_D
     */
    public String getCmMerchandiserD() {
        return (String) getAttributeInternal(CMMERCHANDISERD);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MERCHANDISER_D using the alias name CmMerchandiserD.
     * @param value value to set the CM_MERCHANDISER_D
     */
    public void setCmMerchandiserD(String value) {
        setAttributeInternal(CMMERCHANDISERD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String) getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Buyer.
     * @param value value to set the  Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerCriteria.
     * @return the BuyerCriteria
     */
    public String getBuyerCriteria() {
        return (String) getAttributeInternal(BUYERCRITERIA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerCriteria.
     * @param value value to set the  BuyerCriteria
     */
    public void setBuyerCriteria(String value) {
        setAttributeInternal(BUYERCRITERIA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GmStatus.
     * @return the GmStatus
     */
    public String getGmStatus() {
        return (String) getAttributeInternal(GMSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GmStatus.
     * @param value value to set the  GmStatus
     */
    public void setGmStatus(String value) {
        setAttributeInternal(GMSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MdStatus.
     * @return the MdStatus
     */
    public String getMdStatus() {
        return (String) getAttributeInternal(MDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MdStatus.
     * @param value value to set the  MdStatus
     */
    public void setMdStatus(String value) {
        setAttributeInternal(MDSTATUS, value);
    }

    /**
     * Gets the attribute value for SAMPLE_DOC_NO using the alias name SampleDocNo.
     * @return the SAMPLE_DOC_NO
     */
    public Number getSampleDocNo() {
        return (Number) getAttributeInternal(SAMPLEDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SAMPLE_DOC_NO using the alias name SampleDocNo.
     * @param value value to set the SAMPLE_DOC_NO
     */
    public void setSampleDocNo(Number value) {
        setAttributeInternal(SAMPLEDOCNO, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for VERSION_NO using the alias name VersionNo.
     * @return the VERSION_NO
     */
    public Number getVersionNo() {
        return (Number) getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NO using the alias name VersionNo.
     * @param value value to set the VERSION_NO
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for POC_TYPE using the alias name PocType.
     * @return the POC_TYPE
     */
    public String getPocType() {
        return (String) getAttributeInternal(POCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for POC_TYPE using the alias name PocType.
     * @param value value to set the POC_TYPE
     */
    public void setPocType(String value) {
        setAttributeInternal(POCTYPE, value);
    }

    /**
     * Gets the attribute value for PROD_STYLE_NO using the alias name ProdStyleNo.
     * @return the PROD_STYLE_NO
     */
    public String getProdStyleNo() {
        return (String) getAttributeInternal(PRODSTYLENO);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_STYLE_NO using the alias name ProdStyleNo.
     * @param value value to set the PROD_STYLE_NO
     */
    public void setProdStyleNo(String value) {
        setAttributeInternal(PRODSTYLENO, value);
    }

    /**
     * Gets the attribute value for PROD_COST_LINE_PER_H using the alias name ProdCostLinePerH.
     * @return the PROD_COST_LINE_PER_H
     */
    public Number getProdCostLinePerH() {
        return (Number) getAttributeInternal(PRODCOSTLINEPERH);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_COST_LINE_PER_H using the alias name ProdCostLinePerH.
     * @param value value to set the PROD_COST_LINE_PER_H
     */
    public void setProdCostLinePerH(Number value) {
        setAttributeInternal(PRODCOSTLINEPERH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attachemnt.
     * @return the Attachemnt
     */
    public Number getAttachemnt() {
        return (Number) getAttributeInternal(ATTACHEMNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attachemnt.
     * @param value value to set the  Attachemnt
     */
    public void setAttachemnt(Number value) {
        setAttributeInternal(ATTACHEMNT, value);
    }

    /**
     * Gets the attribute value for DIVISION using the alias name Division.
     * @return the DIVISION
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
     * @param value value to set the DIVISION
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for STYLE_NAME_NEW using the alias name StyleNameNew.
     * @return the STYLE_NAME_NEW
     */
    public String getStyleNameNew() {
        return (String) getAttributeInternal(STYLENAMENEW);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NAME_NEW using the alias name StyleNameNew.
     * @param value value to set the STYLE_NAME_NEW
     */
    public void setStyleNameNew(String value) {
        setAttributeInternal(STYLENAMENEW, value);
    }

    /**
     * Gets the attribute value for ITEM_PURCHASE_TYPE using the alias name ItemPurchaseType.
     * @return the ITEM_PURCHASE_TYPE
     */
    public String getItemPurchaseType() {
        return (String) getAttributeInternal(ITEMPURCHASETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_PURCHASE_TYPE using the alias name ItemPurchaseType.
     * @param value value to set the ITEM_PURCHASE_TYPE
     */
    public void setItemPurchaseType(String value) {
        setAttributeInternal(ITEMPURCHASETYPE, value);
    }

    /**
     * Gets the attribute value for STYLE_TRACKING using the alias name StyleTracking.
     * @return the STYLE_TRACKING
     */
    public String getStyleTracking() {
        return (String) getAttributeInternal(STYLETRACKING);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_TRACKING using the alias name StyleTracking.
     * @param value value to set the STYLE_TRACKING
     */
    public void setStyleTracking(String value) {
        setAttributeInternal(STYLETRACKING, value);
    }

    /**
     * Gets the attribute value for CM_CALCULATION using the alias name CmCalculation.
     * @return the CM_CALCULATION
     */
    public String getCmCalculation() {
        return (String) getAttributeInternal(CMCALCULATION);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_CALCULATION using the alias name CmCalculation.
     * @param value value to set the CM_CALCULATION
     */
    public void setCmCalculation(String value) {
        setAttributeInternal(CMCALCULATION, value);
    }

    /**
     * Gets the attribute value for AGENCY_COMMISSION using the alias name AgencyCommission.
     * @return the AGENCY_COMMISSION
     */
    public String getAgencyCommission() {
        return (String) getAttributeInternal(AGENCYCOMMISSION);
    }

    /**
     * Sets <code>value</code> as attribute value for AGENCY_COMMISSION using the alias name AgencyCommission.
     * @param value value to set the AGENCY_COMMISSION
     */
    public void setAgencyCommission(String value) {
        setAttributeInternal(AGENCYCOMMISSION, value);
    }

    /**
     * Gets the attribute value for TRANSFER_STATUS using the alias name TransferStatus.
     * @return the TRANSFER_STATUS
     */
    public String getTransferStatus() {
        return (String) getAttributeInternal(TRANSFERSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_STATUS using the alias name TransferStatus.
     * @param value value to set the TRANSFER_STATUS
     */
    public void setTransferStatus(String value) {
        setAttributeInternal(TRANSFERSTATUS, value);
    }

    /**
     * Gets the attribute value for TOTAL_BPO_TBA_QTY using the alias name TotalBpoTbaQty.
     * @return the TOTAL_BPO_TBA_QTY
     */
    public String getTotalBpoTbaQty() {
        return (String) getAttributeInternal(TOTALBPOTBAQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_BPO_TBA_QTY using the alias name TotalBpoTbaQty.
     * @param value value to set the TOTAL_BPO_TBA_QTY
     */
    public void setTotalBpoTbaQty(String value) {
        setAttributeInternal(TOTALBPOTBAQTY, value);
    }

    /**
     * Gets the attribute value for BPO_QTY using the alias name BpoQty.
     * @return the BPO_QTY
     */
    public String getBpoQty() {
        return (String) getAttributeInternal(BPOQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_QTY using the alias name BpoQty.
     * @param value value to set the BPO_QTY
     */
    public void setBpoQty(String value) {
        setAttributeInternal(BPOQTY, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgPrecostingLView.
     */
    public RowIterator getMnjMfgPrecostingLView() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGLVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CreateSaleOrderLinesVO.
     */
    public RowIterator getCreateSaleOrderLinesVO() {
        return (RowIterator)getAttributeInternal(CREATESALEORDERLINESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UpdateOrderInterface.
     */
    public RowIterator getUpdateOrderInterface() {
        return (RowIterator)getAttributeInternal(UPDATEORDERINTERFACE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OrderProjectionVO1.
     */
    public RowSet getOrderProjectionVO1() {
        return (RowSet)getAttributeInternal(ORDERPROJECTIONVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OperatingUnits1.
     */
    public RowSet getOperatingUnits1() {
        return (RowSet)getAttributeInternal(OPERATINGUNITS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BuyerLov1.
     */
    public RowSet getBuyerLov1() {
        return (RowSet)getAttributeInternal(BUYERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SeasonLov1.
     */
    public RowSet getSeasonLov1() {
        return (RowSet)getAttributeInternal(SEASONLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> brandLov1.
     */
    public RowSet getbrandLov1() {
        return (RowSet)getAttributeInternal(BRANDLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FitLov1.
     */
    public RowSet getFitLov1() {
        return (RowSet)getAttributeInternal(FITLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EndUserLov1.
     */
    public RowSet getEndUserLov1() {
        return (RowSet)getAttributeInternal(ENDUSERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EndUserLov2.
     */
    public RowSet getEndUserLov2() {
        return (RowSet)getAttributeInternal(ENDUSERLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemDescLov1.
     */
    public RowSet getItemDescLov1() {
        return (RowSet)getAttributeInternal(ITEMDESCLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CostingUOMLov1.
     */
    public RowSet getCostingUOMLov1() {
        return (RowSet)getAttributeInternal(COSTINGUOMLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PocTypeVO1.
     */
    public RowSet getPocTypeVO1() {
        return (RowSet)getAttributeInternal(POCTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DivisionTracking1.
     */
    public RowSet getDivisionTracking1() {
        return (RowSet)getAttributeInternal(DIVISIONTRACKING1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Style_division_tracking_lov1.
     */
    public RowSet getStyle_division_tracking_lov1() {
        return (RowSet)getAttributeInternal(STYLE_DIVISION_TRACKING_LOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemPurchaseTypeLOV1.
     */
    public RowSet getItemPurchaseTypeLOV1() {
        return (RowSet)getAttributeInternal(ITEMPURCHASETYPELOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
