package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 07 12:47:05 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WashProcessWetVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WashProcessWetVOImpl() {
    }
}
