package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 07 12:46:02 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WashProcessDryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WashProcessDryVOImpl() {
    }
}
