package mnj.mfg.model.views.client;

import mnj.mfg.model.views.common.MnjMfgPrecostingLView;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 17:41:02 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingLViewClient extends ViewUsageImpl implements MnjMfgPrecostingLView {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingLViewClient() {
    }

    public void ExecuteLines(String POC) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"ExecuteLines",new String [] {"java.lang.String"},new Object[] {POC});
        return;
    }
}
