package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 22 16:12:28 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgPrecostingLImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void validateEntity() {
        super.validateEntity();

    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        HeaderNumber {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getHeaderNumber();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setHeaderNumber((Number)value);
            }
        }
        ,
        WashName {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWashName();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        Colour {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getColour();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setColour((String)value);
            }
        }
        ,
        Rate {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getRate();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setRate((Number)value);
            }
        }
        ,
        FobWitoutComm {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFobWitoutComm();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFobWitoutComm((Number)value);
            }
        }
        ,
        FobWithComm {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFobWithComm();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFobWithComm((Number)value);
            }
        }
        ,
        FobWithSmsSample {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFobWithSmsSample();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFobWithSmsSample((Number)value);
            }
        }
        ,
        CmMerchandiser {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCmMerchandiser();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCmMerchandiser((Number)value);
            }
        }
        ,
        ReflectProfit {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getReflectProfit();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setReflectProfit((Number)value);
            }
        }
        ,
        Cost {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCost();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCost((Number)value);
            }
        }
        ,
        Finance {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFinance();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFinance((Number)value);
            }
        }
        ,
        Profit {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getProfit();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setProfit((Number)value);
            }
        }
        ,
        Cm {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCm();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCm((Number)value);
            }
        }
        ,
        ProdCostHour {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getProdCostHour();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setProdCostHour((Number)value);
            }
        }
        ,
        ProdPerHour {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getProdPerHour();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setProdPerHour((Number)value);
            }
        }
        ,
        BpoQty {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getBpoQty();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setBpoQty((Number)value);
            }
        }
        ,
        RequestId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getRequestId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setRequestId((Number)value);
            }
        }
        ,
        ItemId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getItemId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        Flag {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFlag();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFlag((String)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        PoType {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getPoType();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setPoType((String)value);
            }
        }
        ,
        OtherCharge {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getOtherCharge();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setOtherCharge((Number)value);
            }
        }
        ,
        LabTestCharge {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getLabTestCharge();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setLabTestCharge((Number)value);
            }
        }
        ,
        Print {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getPrint();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setPrint((Number)value);
            }
        }
        ,
        FabricFinance {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFabricFinance();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFabricFinance((Number)value);
            }
        }
        ,
        WashFinance {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWashFinance();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWashFinance((Number)value);
            }
        }
        ,
        TrimFinance {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getTrimFinance();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setTrimFinance((Number)value);
            }
        }
        ,
        CommisonPrcnt {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCommisonPrcnt();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCommisonPrcnt((Number)value);
            }
        }
        ,
        SmsQty {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getSmsQty();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setSmsQty((Number)value);
            }
        }
        ,
        FabricDesc {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFabricDesc();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFabricDesc((String)value);
            }
        }
        ,
        CloneFlag {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCloneFlag();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCloneFlag((String)value);
            }
        }
        ,
        CloneRowId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCloneRowId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCloneRowId((Number)value);
            }
        }
        ,
        Fob {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFob();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFob((Number)value);
            }
        }
        ,
        FabricCost {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFabricCost();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFabricCost((Number)value);
            }
        }
        ,
        TrimCost {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getTrimCost();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setTrimCost((Number)value);
            }
        }
        ,
        WashCost {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWashCost();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWashCost((Number)value);
            }
        }
        ,
        TargetPrice {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getTargetPrice();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setTargetPrice((Number)value);
            }
        }
        ,
        Difference {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getDifference();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setDifference((Number)value);
            }
        }
        ,
        Others {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getOthers();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setOthers((Number)value);
            }
        }
        ,
        Clasfic {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getClasfic();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setClasfic((String)value);
            }
        }
        ,
        Incoterms {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getIncoterms();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setIncoterms((String)value);
            }
        }
        ,
        Status {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        ChildStyleNo {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getChildStyleNo();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setChildStyleNo((String)value);
            }
        }
        ,
        Weight {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWeight();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWeight((String)value);
            }
        }
        ,
        WeightType {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWeightType();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWeightType((String)value);
            }
        }
        ,
        WidthValue {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWidthValue();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWidthValue((Number)value);
            }
        }
        ,
        WidthType {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getWidthType();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setWidthType((String)value);
            }
        }
        ,
        FabricFinsih {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFabricFinsih();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFabricFinsih((String)value);
            }
        }
        ,
        Elongation {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getElongation();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setElongation((String)value);
            }
        }
        ,
        FabricContent {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFabricContent();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFabricContent((String)value);
            }
        }
        ,
        Country {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCountry();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        DeliveryEndDate {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getDeliveryEndDate();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setDeliveryEndDate((Date)value);
            }
        }
        ,
        DeliveryStartDate {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getDeliveryStartDate();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setDeliveryStartDate((Date)value);
            }
        }
        ,
        ReplaceWash {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getReplaceWash();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setReplaceWash((String)value);
            }
        }
        ,
        ShipMode {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getShipMode();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setShipMode((String)value);
            }
        }
        ,
        ReplaceBpo {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getReplaceBpo();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setReplaceBpo((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        FinalFinishGoodsColour {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFinalFinishGoodsColour();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFinalFinishGoodsColour((String)value);
            }
        }
        ,
        CmMerchand {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCmMerchand();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCmMerchand((String)value);
            }
        }
        ,
        ProdPerLinePerH {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getProdPerLinePerH();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setProdPerLinePerH((Number)value);
            }
        }
        ,
        StyleEfficiency {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getStyleEfficiency();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setStyleEfficiency((Number)value);
            }
        }
        ,
        Sam {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getSam();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setSam((Number)value);
            }
        }
        ,
        Smv {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getSmv();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setSmv((String)value);
            }
        }
        ,
        CostNew {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCostNew();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCostNew((Number)value);
            }
        }
        ,
        FactoryAvgEf {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getFactoryAvgEf();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setFactoryAvgEf((String)value);
            }
        }
        ,
        ProdCostLinePerH {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getProdCostLinePerH();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setProdCostLinePerH((Number)value);
            }
        }
        ,
        TotalCost {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getTotalCost();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setTotalCost((Number)value);
            }
        }
        ,
        CmManagement {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getCmManagement();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setCmManagement((Number)value);
            }
        }
        ,
        SaleLineId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getSaleLineId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setSaleLineId((Number)value);
            }
        }
        ,
        SaleHeaderId {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getSaleHeaderId();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setSaleHeaderId((Number)value);
            }
        }
        ,
        MnjMfgPrecostingH {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getMnjMfgPrecostingH();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setMnjMfgPrecostingH((MnjMfgPrecostingHImpl)value);
            }
        }
        ,
        MnjMfgPrecostingItemD {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getMnjMfgPrecostingItemD();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgPrecostingCountryD {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getMnjMfgPrecostingCountryD();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgPrecostingWetD {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getMnjMfgPrecostingWetD();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgPrecostingDryD {
            public Object get(MnjMfgPrecostingLImpl obj) {
                return obj.getMnjMfgPrecostingDryD();
            }

            public void put(MnjMfgPrecostingLImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgPrecostingLImpl object);

        public abstract void put(MnjMfgPrecostingLImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int HEADERNUMBER = AttributesEnum.HeaderNumber.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int COLOUR = AttributesEnum.Colour.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int FOBWITOUTCOMM = AttributesEnum.FobWitoutComm.index();
    public static final int FOBWITHCOMM = AttributesEnum.FobWithComm.index();
    public static final int FOBWITHSMSSAMPLE = AttributesEnum.FobWithSmsSample.index();
    public static final int CMMERCHANDISER = AttributesEnum.CmMerchandiser.index();
    public static final int REFLECTPROFIT = AttributesEnum.ReflectProfit.index();
    public static final int COST = AttributesEnum.Cost.index();
    public static final int FINANCE = AttributesEnum.Finance.index();
    public static final int PROFIT = AttributesEnum.Profit.index();
    public static final int CM = AttributesEnum.Cm.index();
    public static final int PRODCOSTHOUR = AttributesEnum.ProdCostHour.index();
    public static final int PRODPERHOUR = AttributesEnum.ProdPerHour.index();
    public static final int BPOQTY = AttributesEnum.BpoQty.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int FLAG = AttributesEnum.Flag.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int POTYPE = AttributesEnum.PoType.index();
    public static final int OTHERCHARGE = AttributesEnum.OtherCharge.index();
    public static final int LABTESTCHARGE = AttributesEnum.LabTestCharge.index();
    public static final int PRINT = AttributesEnum.Print.index();
    public static final int FABRICFINANCE = AttributesEnum.FabricFinance.index();
    public static final int WASHFINANCE = AttributesEnum.WashFinance.index();
    public static final int TRIMFINANCE = AttributesEnum.TrimFinance.index();
    public static final int COMMISONPRCNT = AttributesEnum.CommisonPrcnt.index();
    public static final int SMSQTY = AttributesEnum.SmsQty.index();
    public static final int FABRICDESC = AttributesEnum.FabricDesc.index();
    public static final int CLONEFLAG = AttributesEnum.CloneFlag.index();
    public static final int CLONEROWID = AttributesEnum.CloneRowId.index();
    public static final int FOB = AttributesEnum.Fob.index();
    public static final int FABRICCOST = AttributesEnum.FabricCost.index();
    public static final int TRIMCOST = AttributesEnum.TrimCost.index();
    public static final int WASHCOST = AttributesEnum.WashCost.index();
    public static final int TARGETPRICE = AttributesEnum.TargetPrice.index();
    public static final int DIFFERENCE = AttributesEnum.Difference.index();
    public static final int OTHERS = AttributesEnum.Others.index();
    public static final int CLASFIC = AttributesEnum.Clasfic.index();
    public static final int INCOTERMS = AttributesEnum.Incoterms.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CHILDSTYLENO = AttributesEnum.ChildStyleNo.index();
    public static final int WEIGHT = AttributesEnum.Weight.index();
    public static final int WEIGHTTYPE = AttributesEnum.WeightType.index();
    public static final int WIDTHVALUE = AttributesEnum.WidthValue.index();
    public static final int WIDTHTYPE = AttributesEnum.WidthType.index();
    public static final int FABRICFINSIH = AttributesEnum.FabricFinsih.index();
    public static final int ELONGATION = AttributesEnum.Elongation.index();
    public static final int FABRICCONTENT = AttributesEnum.FabricContent.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int DELIVERYENDDATE = AttributesEnum.DeliveryEndDate.index();
    public static final int DELIVERYSTARTDATE = AttributesEnum.DeliveryStartDate.index();
    public static final int REPLACEWASH = AttributesEnum.ReplaceWash.index();
    public static final int SHIPMODE = AttributesEnum.ShipMode.index();
    public static final int REPLACEBPO = AttributesEnum.ReplaceBpo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int FINALFINISHGOODSCOLOUR = AttributesEnum.FinalFinishGoodsColour.index();
    public static final int CMMERCHAND = AttributesEnum.CmMerchand.index();
    public static final int PRODPERLINEPERH = AttributesEnum.ProdPerLinePerH.index();
    public static final int STYLEEFFICIENCY = AttributesEnum.StyleEfficiency.index();
    public static final int SAM = AttributesEnum.Sam.index();
    public static final int SMV = AttributesEnum.Smv.index();
    public static final int COSTNEW = AttributesEnum.CostNew.index();
    public static final int FACTORYAVGEF = AttributesEnum.FactoryAvgEf.index();
    public static final int PRODCOSTLINEPERH = AttributesEnum.ProdCostLinePerH.index();
    public static final int TOTALCOST = AttributesEnum.TotalCost.index();
    public static final int CMMANAGEMENT = AttributesEnum.CmManagement.index();
    public static final int SALELINEID = AttributesEnum.SaleLineId.index();
    public static final int SALEHEADERID = AttributesEnum.SaleHeaderId.index();
    public static final int MNJMFGPRECOSTINGH = AttributesEnum.MnjMfgPrecostingH.index();
    public static final int MNJMFGPRECOSTINGITEMD = AttributesEnum.MnjMfgPrecostingItemD.index();
    public static final int MNJMFGPRECOSTINGCOUNTRYD = AttributesEnum.MnjMfgPrecostingCountryD.index();
    public static final int MNJMFGPRECOSTINGWETD = AttributesEnum.MnjMfgPrecostingWetD.index();
    public static final int MNJMFGPRECOSTINGDRYD = AttributesEnum.MnjMfgPrecostingDryD.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgPrecostingLImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgPrecostingL");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for HeaderNumber, using the alias name HeaderNumber.
     * @return the HeaderNumber
     */
    public Number getHeaderNumber() {
        return (Number)getAttributeInternal(HEADERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderNumber.
     * @param value value to set the HeaderNumber
     */
    public void setHeaderNumber(Number value) {
        setAttributeInternal(HEADERNUMBER, value);
    }

    /**
     * Gets the attribute value for WashName, using the alias name WashName.
     * @return the WashName
     */
    public String getWashName() {
        return (String)getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashName.
     * @param value value to set the WashName
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value.trim());
    }

    /**
     * Gets the attribute value for Colour, using the alias name Colour.
     * @return the Colour
     */
    public String getColour() {
        return (String)getAttributeInternal(COLOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Colour.
     * @param value value to set the Colour
     */
    public void setColour(String value) {
        setAttributeInternal(COLOUR, value.trim());
    }

    /**
     * Gets the attribute value for Rate, using the alias name Rate.
     * @return the Rate
     */
    public Number getRate() {
        return (Number)getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rate.
     * @param value value to set the Rate
     */
    public void setRate(Number value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for FobWitoutComm, using the alias name FobWitoutComm.
     * @return the FobWitoutComm
     */
    public Number getFobWitoutComm() {
        return (Number)getAttributeInternal(FOBWITOUTCOMM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobWitoutComm.
     * @param value value to set the FobWitoutComm
     */
    public void setFobWitoutComm(Number value) {
        setAttributeInternal(FOBWITOUTCOMM, value);
    }

    /**
     * Gets the attribute value for FobWithComm, using the alias name FobWithComm.
     * @return the FobWithComm
     */
    public Number getFobWithComm() {
        return (Number)getAttributeInternal(FOBWITHCOMM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobWithComm.
     * @param value value to set the FobWithComm
     */
    public void setFobWithComm(Number value) {
        setAttributeInternal(FOBWITHCOMM, value);
    }

    /**
     * Gets the attribute value for FobWithSmsSample, using the alias name FobWithSmsSample.
     * @return the FobWithSmsSample
     */
    public Number getFobWithSmsSample() {
        return (Number)getAttributeInternal(FOBWITHSMSSAMPLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobWithSmsSample.
     * @param value value to set the FobWithSmsSample
     */
    public void setFobWithSmsSample(Number value) {
        setAttributeInternal(FOBWITHSMSSAMPLE, value);
    }

    /**
     * Gets the attribute value for CmMerchandiser, using the alias name CmMerchandiser.
     * @return the CmMerchandiser
     */
    public Number getCmMerchandiser() {
        return (Number)getAttributeInternal(CMMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmMerchandiser.
     * @param value value to set the CmMerchandiser
     */
    public void setCmMerchandiser(Number value) {
        setAttributeInternal(CMMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for ReflectProfit, using the alias name ReflectProfit.
     * @return the ReflectProfit
     */
    public Number getReflectProfit() {
        return (Number)getAttributeInternal(REFLECTPROFIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReflectProfit.
     * @param value value to set the ReflectProfit
     */
    public void setReflectProfit(Number value) {
        setAttributeInternal(REFLECTPROFIT, value);
    }

    /**
     * Gets the attribute value for Cost, using the alias name Cost.
     * @return the Cost
     */
    public Number getCost() {
        return (Number)getAttributeInternal(COST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cost.
     * @param value value to set the Cost
     */
    public void setCost(Number value) {
        setAttributeInternal(COST, value);
    }

    /**
     * Gets the attribute value for Finance, using the alias name Finance.
     * @return the Finance
     */
    public Number getFinance() {
        return (Number)getAttributeInternal(FINANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Finance.
     * @param value value to set the Finance
     */
    public void setFinance(Number value) {
        setAttributeInternal(FINANCE, value);
    }

    /**
     * Gets the attribute value for Profit, using the alias name Profit.
     * @return the Profit
     */
    public Number getProfit() {
        return (Number)getAttributeInternal(PROFIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Profit.
     * @param value value to set the Profit
     */
    public void setProfit(Number value) {
        setAttributeInternal(PROFIT, value);
    }

    /**
     * Gets the attribute value for Cm, using the alias name Cm.
     * @return the Cm
     */
    public Number getCm() {
        return (Number)getAttributeInternal(CM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cm.
     * @param value value to set the Cm
     */
    public void setCm(Number value) {
        setAttributeInternal(CM, value);
    }

    /**
     * Gets the attribute value for ProdCostHour, using the alias name ProdCostHour.
     * @return the ProdCostHour
     */
    public Number getProdCostHour() {
        return (Number)getAttributeInternal(PRODCOSTHOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdCostHour.
     * @param value value to set the ProdCostHour
     */
    public void setProdCostHour(Number value) {
        setAttributeInternal(PRODCOSTHOUR, value);
    }

    /**
     * Gets the attribute value for ProdPerHour, using the alias name ProdPerHour.
     * @return the ProdPerHour
     */
    public Number getProdPerHour() {
        return (Number)getAttributeInternal(PRODPERHOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdPerHour.
     * @param value value to set the ProdPerHour
     */
    public void setProdPerHour(Number value) {
        setAttributeInternal(PRODPERHOUR, value);
    }

    /**
     * Gets the attribute value for BpoQty, using the alias name BpoQty.
     * @return the BpoQty
     */
    public Number getBpoQty() {
        return (Number)getAttributeInternal(BPOQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoQty.
     * @param value value to set the BpoQty
     */
    public void setBpoQty(Number value) {
        setAttributeInternal(BPOQTY, value);
    }

    /**
     * Gets the attribute value for RequestId, using the alias name RequestId.
     * @return the RequestId
     */
    public Number getRequestId() {
        return (Number)getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestId.
     * @param value value to set the RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for Flag, using the alias name Flag.
     * @return the Flag
     */
    public String getFlag() {
        return (String)getAttributeInternal(FLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flag.
     * @param value value to set the Flag
     */
    public void setFlag(String value) {
        setAttributeInternal(FLAG, value);
    }

    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value.trim());
    }

    /**
     * Gets the attribute value for PoType, using the alias name PoType.
     * @return the PoType
     */
    public String getPoType() {
        return (String)getAttributeInternal(POTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoType.
     * @param value value to set the PoType
     */
    public void setPoType(String value) {
        setAttributeInternal(POTYPE, value);
    }

    /**
     * Gets the attribute value for OtherCharge, using the alias name OtherCharge.
     * @return the OtherCharge
     */
    public Number getOtherCharge() {
        return (Number)getAttributeInternal(OTHERCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtherCharge.
     * @param value value to set the OtherCharge
     */
    public void setOtherCharge(Number value) {
        setAttributeInternal(OTHERCHARGE, value);
    }

    /**
     * Gets the attribute value for LabTestCharge, using the alias name LabTestCharge.
     * @return the LabTestCharge
     */
    public Number getLabTestCharge() {
        return (Number)getAttributeInternal(LABTESTCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LabTestCharge.
     * @param value value to set the LabTestCharge
     */
    public void setLabTestCharge(Number value) {
        setAttributeInternal(LABTESTCHARGE, value);
    }

    /**
     * Gets the attribute value for Print, using the alias name Print.
     * @return the Print
     */
    public Number getPrint() {
        return (Number)getAttributeInternal(PRINT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Print.
     * @param value value to set the Print
     */
    public void setPrint(Number value) {
        setAttributeInternal(PRINT, value);
    }

    /**
     * Gets the attribute value for FabricFinance, using the alias name FabricFinance.
     * @return the FabricFinance
     */
    public Number getFabricFinance() {
        return (Number)getAttributeInternal(FABRICFINANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricFinance.
     * @param value value to set the FabricFinance
     */
    public void setFabricFinance(Number value) {
        setAttributeInternal(FABRICFINANCE, value);
    }

    /**
     * Gets the attribute value for WashFinance, using the alias name WashFinance.
     * @return the WashFinance
     */
    public Number getWashFinance() {
        return (Number)getAttributeInternal(WASHFINANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashFinance.
     * @param value value to set the WashFinance
     */
    public void setWashFinance(Number value) {
        setAttributeInternal(WASHFINANCE, value);
    }

    /**
     * Gets the attribute value for TrimFinance, using the alias name TrimFinance.
     * @return the TrimFinance
     */
    public Number getTrimFinance() {
        return (Number)getAttributeInternal(TRIMFINANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrimFinance.
     * @param value value to set the TrimFinance
     */
    public void setTrimFinance(Number value) {
        setAttributeInternal(TRIMFINANCE, value);
    }

    /**
     * Gets the attribute value for CommisonPrcnt, using the alias name CommisonPrcnt.
     * @return the CommisonPrcnt
     */
    public Number getCommisonPrcnt() {
        return (Number)getAttributeInternal(COMMISONPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommisonPrcnt.
     * @param value value to set the CommisonPrcnt
     */
    public void setCommisonPrcnt(Number value) {
        setAttributeInternal(COMMISONPRCNT, value);
    }

    /**
     * Gets the attribute value for SmsQty, using the alias name SmsQty.
     * @return the SmsQty
     */
    public Number getSmsQty() {
        return (Number)getAttributeInternal(SMSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SmsQty.
     * @param value value to set the SmsQty
     */
    public void setSmsQty(Number value) {
        setAttributeInternal(SMSQTY, value);
    }

    /**
     * Gets the attribute value for FabricDesc, using the alias name FabricDesc.
     * @return the FabricDesc
     */
    public String getFabricDesc() {
        return (String)getAttributeInternal(FABRICDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricDesc.
     * @param value value to set the FabricDesc
     */
    public void setFabricDesc(String value) {
        setAttributeInternal(FABRICDESC, value.trim());
    }

    /**
     * Gets the attribute value for CloneFlag, using the alias name CloneFlag.
     * @return the CloneFlag
     */
    public String getCloneFlag() {
        return (String)getAttributeInternal(CLONEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for CloneFlag.
     * @param value value to set the CloneFlag
     */
    public void setCloneFlag(String value) {
        setAttributeInternal(CLONEFLAG, value);
    }

    /**
     * Gets the attribute value for CloneRowId, using the alias name CloneRowId.
     * @return the CloneRowId
     */
    public Number getCloneRowId() {
        return (Number)getAttributeInternal(CLONEROWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CloneRowId.
     * @param value value to set the CloneRowId
     */
    public void setCloneRowId(Number value) {
        setAttributeInternal(CLONEROWID, value);
    }

    /**
     * Gets the attribute value for Fob, using the alias name Fob.
     * @return the Fob
     */
    public Number getFob() {
        return (Number)getAttributeInternal(FOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fob.
     * @param value value to set the Fob
     */
    public void setFob(Number value) {
        setAttributeInternal(FOB, value);
    }

    /**
     * Gets the attribute value for FabricCost, using the alias name FabricCost.
     * @return the FabricCost
     */
    public Number getFabricCost() {
        return (Number)getAttributeInternal(FABRICCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricCost.
     * @param value value to set the FabricCost
     */
    public void setFabricCost(Number value) {
        setAttributeInternal(FABRICCOST, value);
    }

    /**
     * Gets the attribute value for TrimCost, using the alias name TrimCost.
     * @return the TrimCost
     */
    public Number getTrimCost() {
        return (Number)getAttributeInternal(TRIMCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrimCost.
     * @param value value to set the TrimCost
     */
    public void setTrimCost(Number value) {
        setAttributeInternal(TRIMCOST, value);
    }

    /**
     * Gets the attribute value for WashCost, using the alias name WashCost.
     * @return the WashCost
     */
    public Number getWashCost() {
        return (Number)getAttributeInternal(WASHCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashCost.
     * @param value value to set the WashCost
     */
    public void setWashCost(Number value) {
        setAttributeInternal(WASHCOST, value);
    }

    /**
     * Gets the attribute value for TargetPrice, using the alias name TargetPrice.
     * @return the TargetPrice
     */
    public Number getTargetPrice() {
        return (Number)getAttributeInternal(TARGETPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TargetPrice.
     * @param value value to set the TargetPrice
     */
    public void setTargetPrice(Number value) {
        setAttributeInternal(TARGETPRICE, value);
    }

    /**
     * Gets the attribute value for Difference, using the alias name Difference.
     * @return the Difference
     */
    public Number getDifference() {
        return (Number)getAttributeInternal(DIFFERENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Difference.
     * @param value value to set the Difference
     */
    public void setDifference(Number value) {
        setAttributeInternal(DIFFERENCE, value);
    }

    /**
     * Gets the attribute value for Others, using the alias name Others.
     * @return the Others
     */
    public Number getOthers() {
        return (Number)getAttributeInternal(OTHERS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Others.
     * @param value value to set the Others
     */
    public void setOthers(Number value) {
        setAttributeInternal(OTHERS, value);
    }

    /**
     * Gets the attribute value for Clasfic, using the alias name Clasfic.
     * @return the Clasfic
     */
    public String getClasfic() {
        return (String)getAttributeInternal(CLASFIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Clasfic.
     * @param value value to set the Clasfic
     */
    public void setClasfic(String value) {
        setAttributeInternal(CLASFIC, value);
    }

    /**
     * Gets the attribute value for Incoterms, using the alias name Incoterms.
     * @return the Incoterms
     */
    public String getIncoterms() {
        return (String)getAttributeInternal(INCOTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Incoterms.
     * @param value value to set the Incoterms
     */
    public void setIncoterms(String value) {
        setAttributeInternal(INCOTERMS, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ChildStyleNo, using the alias name ChildStyleNo.
     * @return the ChildStyleNo
     */
    public String getChildStyleNo() {
        return (String)getAttributeInternal(CHILDSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChildStyleNo.
     * @param value value to set the ChildStyleNo
     */
    public void setChildStyleNo(String value) {
        setAttributeInternal(CHILDSTYLENO, value.trim());
    }

    /**
     * Gets the attribute value for Weight, using the alias name Weight.
     * @return the Weight
     */
    public String getWeight() {
        return (String)getAttributeInternal(WEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Weight.
     * @param value value to set the Weight
     */
    public void setWeight(String value) {
        setAttributeInternal(WEIGHT, value);
    }

    /**
     * Gets the attribute value for WeightType, using the alias name WeightType.
     * @return the WeightType
     */
    public String getWeightType() {
        return (String)getAttributeInternal(WEIGHTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeightType.
     * @param value value to set the WeightType
     */
    public void setWeightType(String value) {
        setAttributeInternal(WEIGHTTYPE, value);
    }

    /**
     * Gets the attribute value for WidthValue, using the alias name WidthValue.
     * @return the WidthValue
     */
    public Number getWidthValue() {
        return (Number)getAttributeInternal(WIDTHVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WidthValue.
     * @param value value to set the WidthValue
     */
    public void setWidthValue(Number value) {
        setAttributeInternal(WIDTHVALUE, value);
    }

    /**
     * Gets the attribute value for WidthType, using the alias name WidthType.
     * @return the WidthType
     */
    public String getWidthType() {
        return (String)getAttributeInternal(WIDTHTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WidthType.
     * @param value value to set the WidthType
     */
    public void setWidthType(String value) {
        setAttributeInternal(WIDTHTYPE, value);
    }

    /**
     * Gets the attribute value for FabricFinsih, using the alias name FabricFinsih.
     * @return the FabricFinsih
     */
    public String getFabricFinsih() {
        return (String)getAttributeInternal(FABRICFINSIH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricFinsih.
     * @param value value to set the FabricFinsih
     */
    public void setFabricFinsih(String value) {
        setAttributeInternal(FABRICFINSIH, value);
    }

    /**
     * Gets the attribute value for Elongation, using the alias name Elongation.
     * @return the Elongation
     */
    public String getElongation() {
        return (String)getAttributeInternal(ELONGATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Elongation.
     * @param value value to set the Elongation
     */
    public void setElongation(String value) {
        setAttributeInternal(ELONGATION, value);
    }

    /**
     * Gets the attribute value for FabricContent, using the alias name FabricContent.
     * @return the FabricContent
     */
    public String getFabricContent() {
        return (String)getAttributeInternal(FABRICCONTENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricContent.
     * @param value value to set the FabricContent
     */
    public void setFabricContent(String value) {
        setAttributeInternal(FABRICCONTENT, value.trim());
    }


    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for DeliveryEndDate, using the alias name DeliveryEndDate.
     * @return the DeliveryEndDate
     */
    public Date getDeliveryEndDate() {
        return (Date)getAttributeInternal(DELIVERYENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryEndDate.
     * @param value value to set the DeliveryEndDate
     */
    public void setDeliveryEndDate(Date value) {
        setAttributeInternal(DELIVERYENDDATE, value);
    }

    /**
     * Gets the attribute value for DeliveryStartDate, using the alias name DeliveryStartDate.
     * @return the DeliveryStartDate
     */
    public Date getDeliveryStartDate() {
        return (Date)getAttributeInternal(DELIVERYSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryStartDate.
     * @param value value to set the DeliveryStartDate
     */
    public void setDeliveryStartDate(Date value) {
        setAttributeInternal(DELIVERYSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ReplaceWash, using the alias name ReplaceWash.
     * @return the ReplaceWash
     */
    public String getReplaceWash() {
        return (String)getAttributeInternal(REPLACEWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReplaceWash.
     * @param value value to set the ReplaceWash
     */
    public void setReplaceWash(String value) {
        setAttributeInternal(REPLACEWASH, value);
    }

    /**
     * Gets the attribute value for ShipMode, using the alias name ShipMode.
     * @return the ShipMode
     */
    public String getShipMode() {
        return (String)getAttributeInternal(SHIPMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipMode.
     * @param value value to set the ShipMode
     */
    public void setShipMode(String value) {
        setAttributeInternal(SHIPMODE, value);
    }

    /**
     * Gets the attribute value for ReplaceBpo, using the alias name ReplaceBpo.
     * @return the ReplaceBpo
     */
    public String getReplaceBpo() {
        return (String)getAttributeInternal(REPLACEBPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReplaceBpo.
     * @param value value to set the ReplaceBpo
     */
    public void setReplaceBpo(String value) {
        setAttributeInternal(REPLACEBPO, value.trim());
    }


    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for FinalFinishGoodsColour, using the alias name FinalFinishGoodsColour.
     * @return the FinalFinishGoodsColour
     */
    public String getFinalFinishGoodsColour() {
        return (String)getAttributeInternal(FINALFINISHGOODSCOLOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalFinishGoodsColour.
     * @param value value to set the FinalFinishGoodsColour
     */
    public void setFinalFinishGoodsColour(String value) {
        setAttributeInternal(FINALFINISHGOODSCOLOUR, value.trim());
    }

    /**
     * Gets the attribute value for CmMerchand, using the alias name CmMerchand.
     * @return the CmMerchand
     */
    public String getCmMerchand() {
        return (String)getAttributeInternal(CMMERCHAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmMerchand.
     * @param value value to set the CmMerchand
     */
    public void setCmMerchand(String value) {
        setAttributeInternal(CMMERCHAND, value.trim());
    }

    /**
     * Gets the attribute value for ProdPerLinePerH, using the alias name ProdPerLinePerH.
     * @return the ProdPerLinePerH
     */
    public Number getProdPerLinePerH() {
        return (Number)getAttributeInternal(PRODPERLINEPERH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdPerLinePerH.
     * @param value value to set the ProdPerLinePerH
     */
    public void setProdPerLinePerH(Number value) {
        setAttributeInternal(PRODPERLINEPERH, value);
    }

    /**
     * Gets the attribute value for StyleEfficiency, using the alias name StyleEfficiency.
     * @return the StyleEfficiency
     */
    public Number getStyleEfficiency() {
        return (Number)getAttributeInternal(STYLEEFFICIENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleEfficiency.
     * @param value value to set the StyleEfficiency
     */
    public void setStyleEfficiency(Number value) {
        setAttributeInternal(STYLEEFFICIENCY, value);
    }

    /**
     * Gets the attribute value for Sam, using the alias name Sam.
     * @return the Sam
     */
    public Number getSam() {
        return (Number)getAttributeInternal(SAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sam.
     * @param value value to set the Sam
     */
    public void setSam(Number value) {
        setAttributeInternal(SAM, value);
    }

    /**
     * Gets the attribute value for Smv, using the alias name Smv.
     * @return the Smv
     */
    public String getSmv() {
        return (String)getAttributeInternal(SMV);
    }

    /**
     * Sets <code>value</code> as the attribute value for Smv.
     * @param value value to set the Smv
     */
    public void setSmv(String value) {
        setAttributeInternal(SMV, value);
    }

    /**
     * Gets the attribute value for CostNew, using the alias name CostNew.
     * @return the CostNew
     */
    public Number getCostNew() {
        return (Number)getAttributeInternal(COSTNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostNew.
     * @param value value to set the CostNew
     */
    public void setCostNew(Number value) {
        setAttributeInternal(COSTNEW, value);
    }

    /**
     * Gets the attribute value for FactoryAvgEf, using the alias name FactoryAvgEf.
     * @return the FactoryAvgEf
     */
    public String getFactoryAvgEf() {
        return (String)getAttributeInternal(FACTORYAVGEF);
    }

    /**
     * Sets <code>value</code> as the attribute value for FactoryAvgEf.
     * @param value value to set the FactoryAvgEf
     */
    public void setFactoryAvgEf(String value) {
        setAttributeInternal(FACTORYAVGEF, value);
    }

    /**
     * Gets the attribute value for ProdCostLinePerH, using the alias name ProdCostLinePerH.
     * @return the ProdCostLinePerH
     */
    public Number getProdCostLinePerH() {
        return (Number)getAttributeInternal(PRODCOSTLINEPERH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdCostLinePerH.
     * @param value value to set the ProdCostLinePerH
     */
    public void setProdCostLinePerH(Number value) {
        setAttributeInternal(PRODCOSTLINEPERH, value);
    }

    /**
     * Gets the attribute value for TotalCost, using the alias name TotalCost.
     * @return the TotalCost
     */
    public Number getTotalCost() {
        return (Number)getAttributeInternal(TOTALCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalCost.
     * @param value value to set the TotalCost
     */
    public void setTotalCost(Number value) {
        setAttributeInternal(TOTALCOST, value);
    }

    /**
     * Gets the attribute value for CmManagement, using the alias name CmManagement.
     * @return the CmManagement
     */
    public Number getCmManagement() {
        return (Number)getAttributeInternal(CMMANAGEMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmManagement.
     * @param value value to set the CmManagement
     */
    public void setCmManagement(Number value) {
        setAttributeInternal(CMMANAGEMENT, value);
    }

    /**
     * Gets the attribute value for SaleLineId, using the alias name SaleLineId.
     * @return the SaleLineId
     */
    public Number getSaleLineId() {
        return (Number)getAttributeInternal(SALELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleLineId.
     * @param value value to set the SaleLineId
     */
    public void setSaleLineId(Number value) {
        setAttributeInternal(SALELINEID, value);
    }

    /**
     * Gets the attribute value for SaleHeaderId, using the alias name SaleHeaderId.
     * @return the SaleHeaderId
     */
    public Number getSaleHeaderId() {
        return (Number)getAttributeInternal(SALEHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleHeaderId.
     * @param value value to set the SaleHeaderId
     */
    public void setSaleHeaderId(Number value) {
        setAttributeInternal(SALEHEADERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgPrecostingHImpl.
     */
    public MnjMfgPrecostingHImpl getMnjMfgPrecostingH() {
        return (MnjMfgPrecostingHImpl)getAttributeInternal(MNJMFGPRECOSTINGH);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgPrecostingHImpl.
     */
    public void setMnjMfgPrecostingH(MnjMfgPrecostingHImpl value) {
        setAttributeInternal(MNJMFGPRECOSTINGH, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgPrecostingItemD() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGITEMD);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgPrecostingCountryD() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGCOUNTRYD);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgPrecostingWetD() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGWETD);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgPrecostingDryD() {
        return (RowIterator)getAttributeInternal(MNJMFGPRECOSTINGDRYD);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_PRECOSTING_L_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setLineId(sVal);
       // setProdCostHour(new oracle.jbo.domain.Number(getCostAmount()));
       // setHeaderNumber(new Number(getSrNoString()));
    }
//    public int getSrNoString() {
//      int srno = 0;
//      String stmt = "BEGIN :1 := cust_mnj_ont_pkg.cust_mnj_precosting_lines_srno(:2); end;";
//      java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
//      try {
//          cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
//          cs.setInt(2, getHeaderId().intValue());
//          cs.execute();
//          srno = cs.getInt(1);
//          cs.close();
//      } catch (Exception e) {
//          e.printStackTrace();
//      }
//      return srno;
//    }
    
    
//    public int getCostAmount() {
//      int srno = 0;
//      String stmt = "BEGIN :1 := mnj_get_preccost_cost_per_hour; end;";
//      java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
//      try {
//          cs.registerOutParameter(1, OracleTypes.NUMBER);
//          cs.execute();
//          srno = cs.getInt(1);
//          cs.close();
//      } catch (Exception e) {
//          e.printStackTrace();
//      }
//      return srno;
//    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
